/* File generated by Đức's ClasHStamP */
#define __PhxDampedSpring_INTERNAL__
#include "CommonInclude.h"
#include "PhxDampedSpring.h"
/** @public @memberof PhxDampedSpring */
static void PhxDampedSpring_apply(
    PhxJoint* pPhxJoint,
    Sprite* target
){
    PhxDampedSpring* pPhxDampedSpring = ( PhxDampedSpring* )pPhxJoint;
} /* PhxDampedSpring_apply */

PhxJoint* PhxDampedSpring_Copy( PhxDampedSpring* pPhxDampedSpring, const PhxDampedSpring* pSource ){
    PhxJoint_Copy( ( PhxJoint* )pPhxDampedSpring, ( PhxJoint* )pSource );
    return ( PhxJoint* )pPhxDampedSpring;
}
const PhxJointVtbl gPhxDampedSpringVtbl = {
    .papply                      = PhxDampedSpring_apply,
};
