/* File generated by Đức's ClasHStamP */
#define __PhxSlideJoint_INTERNAL__
#include "CommonInclude.h"
#include "PhxSlideJoint.h"
/** @public @memberof PhxSlideJoint */
static void PhxSlideJoint_apply(
    PhxSlideJoint* pPhxSlideJoint,
    Sprite* target
){
} /* PhxSlideJoint_apply */

PhxJoint* PhxSlideJoint_Copy( PhxSlideJoint* pPhxSlideJoint, const PhxSlideJoint* pSource ){
    PhxJoint_Copy( ( PhxJoint* )pPhxSlideJoint, ( PhxJoint* )pSource );
    return ( PhxJoint* )pPhxSlideJoint;
}
const PhxJointVtbl gPhxSlideJointVtbl = {
    .papply                      = PhxSlideJoint_apply,
};
