/* File generated by Đức's ClasHStamP */
#define __Sprite_INTERNAL__
#include "CommonInclude.h"
#include "Sprite.h"
/** @public @pure @memberof Sprite */
void Sprite_draw0(
    Sprite* pSprite,
    SDL_Renderer* renderer
){
    if( pSprite->vTbl == NULL || pSprite->vTbl->pdraw0 == NULL ){ return; }
    pSprite->vTbl->pdraw0( pSprite, renderer );
} /* Sprite_draw0 */

/** @public @pure @memberof Sprite */
void Sprite_update(
    Sprite* pSprite
){
    if( pSprite->vTbl == NULL || pSprite->vTbl->pupdate == NULL ){ return; }
    pSprite->vTbl->pupdate( pSprite );
} /* Sprite_update */

/** @public @pure @memberof Sprite */
void Sprite_updateMouseState(
    Sprite* pSprite,
    int x,
    int y,
    int mouseEvent
){
    if( pSprite->vTbl == NULL || pSprite->vTbl->pupdateMouseState == NULL ){ return; }
    pSprite->vTbl->pupdateMouseState( pSprite, x, y, mouseEvent );
} /* Sprite_updateMouseState */

/** @public @pure @memberof Sprite */
void Sprite_draw1(
    Sprite* pSprite,
    SDL_Renderer* renderer
){
    if( pSprite->vTbl == NULL || pSprite->vTbl->pdraw1 == NULL ){ return; }
    pSprite->vTbl->pdraw1( pSprite, renderer );
} /* Sprite_draw1 */

/** @public @pure @memberof Sprite */
bool Sprite_load(
    Sprite* pSprite,
    SDL_Renderer* renderer
){
    if( pSprite->vTbl == NULL || pSprite->vTbl->pload == NULL ){ return ( bool )0; }
    return pSprite->vTbl->pload( pSprite, renderer );
} /* Sprite_load */

/** @public @pure @memberof Sprite */
void Sprite_free(
    Sprite* pSprite
){
    if( pSprite->vTbl == NULL || pSprite->vTbl->pfree == NULL ){ return; }
    pSprite->vTbl->pfree( pSprite );
} /* Sprite_free */

/** @public @memberof Sprite */
bool Sprite_isUpdated(
    Sprite* pSprite
){
    return pSprite->m_updated;
} /* Sprite_isUpdated */

/** @public @memberof Sprite */
SDL_Rect* Sprite_getRect(
    Sprite* pSprite
){
    return &pSprite->m_rect;
} /* Sprite_getRect */

Sprite* Sprite_Copy( Sprite* pSprite, const Sprite* pSource ){
    pSprite->m_iniRect = pSource->m_iniRect;
    pSprite->m_name = pSource->m_name;
    pSprite->m_imgPath = pSource->m_imgPath;
    pSprite->m_image = pSource->m_image;
    pSprite->m_rect = pSource->m_rect;
    pSprite->m_updated = pSource->m_updated;
    pSprite->m_angle = pSource->m_angle;
    pSprite->m_offset = pSource->m_offset;
    pSprite->m_brightness = pSource->m_brightness;
    pSprite->m_stmUpdated = pSource->m_stmUpdated;
    pSprite->m_stmTexture = pSource->m_stmTexture;
    pSprite->m_stmWindow = pSource->m_stmWindow;
    pSprite->m_stmShow = pSource->m_stmShow;
    return ( Sprite* )pSprite;
}
