/* File generated by Đức's ClasHStamP */
#define __TrackToConstraint_INTERNAL__
#include "CommonInclude.h"
#include "TrackToConstraint.h"
/** @public @memberof TrackToConstraint */
static void TrackToConstraint_apply(
    TrackToConstraint* pTrackToConstraint,
    Sprite* target
){
    if( pTrackToConstraint->m_influence == 0 ){
        return;
    }

    ImgSprite* pSource = ( ImgSprite* )*pTrackToConstraint->m_source;
    ImgSprite* pTarget = ( ImgSprite* )target;
    
    const SDL_Point* pSourceCenter = Sprite_getCenter( pSource );
    const SDL_Point* pTargetCenter = Sprite_getCenter( pTarget );

    double dx = pTargetCenter->x - pSourceCenter->x;
    double dy = pTargetCenter->y - pSourceCenter->y;
    double angle = atan2(dy, dx) * 180.0f / M_PI;

    // Set the source's rotation to face the target
    ImgSprite_setRotation( pSource, angle );

} /* TrackToConstraint_apply */

TransformConstraint* TrackToConstraint_Copy( TrackToConstraint* pTrackToConstraint, const TrackToConstraint* pSource ){
    TransformConstraint_Copy( ( TransformConstraint* )pTrackToConstraint, ( TransformConstraint* )pSource );
    return ( Constraint* )pTrackToConstraint;
}
const ConstraintVtbl gTrackToConstraintVtbl = {
    .papply                      = TrackToConstraint_apply,
};
