/* File generated by Đức's ClasHStamP */
#define __HdStateMachine_INTERNAL__
#include "CommonInclude.h"
#include "HdStateMachine.h"
/** @public @memberof HdStateMachine */
int HdStateMachine_Enterable(
    HdStateMachine* pHdStateMachine,
    uint64_t nThisState
){
} /* HdStateMachine_Enterable */

/** @public @memberof HdStateMachine */
int HdStateMachine_Exitable(
    HdStateMachine* pHdStateMachine,
    uint64_t nThisState
){
} /* HdStateMachine_Exitable */

HdStateMachine* HdStateMachine_Copy( HdStateMachine* pHdStateMachine, const HdStateMachine* pSource ){
    pHdStateMachine->pParentStm = pSource->pParentStm;
    pHdStateMachine->nCurrentState = pSource->nCurrentState;
    pHdStateMachine->nLCAState = pSource->nLCAState;
    pHdStateMachine->nTargetState = pSource->nTargetState;
    pHdStateMachine->nSourceState = pSource->nSourceState;
    pHdStateMachine->nPseudostate = pSource->nPseudostate;
    pHdStateMachine->bIsExternTrans = pSource->bIsExternTrans;
    pHdStateMachine->m_stmImage = pSource->m_stmImage;
    pHdStateMachine->m_stmRect = pSource->m_stmRect;
    return ( HdStateMachine* )pHdStateMachine;
}
