/* File generated by Đức's ClasHStamP */
#define __Sprite_INTERNAL__
#include "CommonInclude.h"
#include "Sprite.h"
/** @public @memberof Sprite */
void Sprite_addConstraint(
    Sprite* pSprite,
    Constraint* constraint
){

} /* Sprite_addConstraint */

/** @public @memberof Sprite */
void Sprite_translate(
    Sprite* pSprite,
    int dx,
    int dy
){
} /* Sprite_translate */

/** @public @memberof Sprite */
void Sprite_rotate(
    Sprite* pSprite,
    double dAngle
){
} /* Sprite_rotate */

/** @public @memberof Sprite */
void Sprite_draw(
    Sprite* pSprite,
    SDL_Surface* screenSurface
){
    //SDL_Rect destRect = { pSprite->m_x, pSprite->m_y, pSprite->m_image->w, pSprite->m_image->h };
    SDL_Rect destRect = { 
        pSprite->m_iniRect.x * screenSurface->w, 
        pSprite->m_iniRect.y * screenSurface->h, 
        pSprite->m_iniRect.w  * screenSurface->w, 
        pSprite->m_iniRect.h  * screenSurface->h 
    };
    // Rotate and scale the image
    SDL_Surface* transformedSurface = rotozoomSurfaceXY(
        pSprite->m_image, 
        0., 
        ( double )destRect.w / pSprite->m_image->w,
        ( double )destRect.h / pSprite->m_image->h,
        0
    );

    SDL_BlitSurface(transformedSurface, NULL, screenSurface, &destRect);

    SDL_FreeSurface(transformedSurface);
} /* Sprite_draw */

/** @public @memberof Sprite */
bool Sprite_load(
    Sprite* pSprite
){
    pSprite->m_image = IMG_Load(pSprite->m_imgPath);
    if (!pSprite->m_image) {
        printf("Failed to load image: %s\n", IMG_GetError());
        return false;
    }
    return true;
} /* Sprite_load */

/** @public @memberof Sprite */
void Sprite_free(
    Sprite* pSprite
){
    if (pSprite->m_image) {
        SDL_FreeSurface(pSprite->m_image);
    }
} /* Sprite_free */

Sprite* Sprite_Copy( Sprite* pSprite, const Sprite* pSource ){
    pSprite->m_iniRect = pSource->m_iniRect;
    pSprite->m_imgPath = pSource->m_imgPath;
    pSprite->m_image = pSource->m_image;
    pSprite->m_x = pSource->m_x;
    pSprite->m_y = pSource->m_y;
    pSprite->m_angle = pSource->m_angle;
    memcpy( pSprite->m_constraints, pSource->m_constraints, sizeof( pSprite->m_constraints ) );
    pSprite->m_constraintCount = pSource->m_constraintCount;
    return ( Sprite* )pSprite;
}
