/* File generated by Đức's ClasHStamP */
#define __ContextImpl_INTERNAL__
#include "CommonInclude.h"
#include "ContextImpl.h"
/** @protected @memberof ContextImpl */
static void ContextImpl_protectedMethod(
    BaseClass* pBaseClass
){
} /* ContextImpl_protectedMethod */

boolean ContextImpl_checkE1Params(
    EventParams* e
){
} /* ContextImpl_checkE1Params */

Context* ContextImpl_Copy( ContextImpl* pContextImpl, const ContextImpl* pSource ){
    Context_Copy( ( Context* )pContextImpl, ( Context* )pSource );
    return ( BaseClass* )pContextImpl;
}
const BaseClassVtbl gContextImplVtbl = {
    .pprotectedMethod            = ContextImpl_protectedMethod,
};
