/* File generated by Đức's ClasHStamP */
#define __ContextImpl_INTERNAL__
#include "CommonInclude.h"
#include "ContextImpl.h"
/** @private @static @memberof ContextImpl */
static ContextImpl contextImpl = ContextImpl_Ctor( 4, "", 1, 2, 3, { 0 }, Composition_Ctor( 3 ) );
/** @protected @memberof ContextImpl */
static void ContextImpl_protectedMethod(
    ContextImpl* pContextImpl
){
} /* ContextImpl_protectedMethod */

boolean ContextImpl_checkE1Params(
    EventParams* e
){
} /* ContextImpl_checkE1Params */

Context* ContextImpl_Copy( ContextImpl* pContextImpl, const ContextImpl* pSource ){
    Context_Copy( ( Context* )pContextImpl, ( Context* )pSource );
    return ( BaseClass* )pContextImpl;
}
const BaseClassVtbl gContextImplVtbl = {
    .pprotectedMethod            = ContextImpl_protectedMethod,
};
