/* File generated by Đức's ClasHStamP */
#include "CarBody.c"

#define MAX_HSM         ( 64 )
typedef struct PatternNode {
    int eventId; // ← Track the associated event
    uint64_t statePattern[ MAX_HSM ];  // UINT64_MAX = "Don't Care"
    struct PatternNode* next;
} PatternNode;

static PatternNode* handledPatterns = NULL;
static int g_eventId;
static void* g_pParams;
static HsmStates** g_activeHsmStates = NULL;

static bool isRedundantPattern( HsmStates** hsmStates ) {
    for( PatternNode* node = handledPatterns; node; node = node->next ) {
        bool match = true;
        for( int i = 0; hsmStates[ i ]; i++ ) {
            if( node->statePattern[ i ] != STATE_UNDEF &&  // STATE_UNDEF = "Don't care"
                node->statePattern[ i ] != hsmStates[ i ]->currentState ) {
                match = false;
                break;
            }
        }
        if( match ) return true;
    }
    return false;
}

static void freeHandledPatterns( void ) {
    PatternNode* current = handledPatterns;
    while( current != NULL ) {
        PatternNode* next = current->next;
        free( current );                // free the node itself
        current = next;
    }
    handledPatterns = NULL;
}

static void addPattern( HsmStates** hsmStates ) {
    PatternNode* node = malloc( sizeof( PatternNode ) );
    if( node ){
        for( int i = 0; hsmStates[ i ]; i++ ) {
            node->statePattern[ i ] = ( hsmStates[ i ]->wasQueried || hsmStates[ i ]->pHsm->bHandled ) ? hsmStates[ i ]->currentState : STATE_UNDEF;
        }
        node->next = handledPatterns;
        handledPatterns = node;
    }
}
static void MainTop_printTestCases( CarBody* pContext, MainTop* pUsm, int eventId, void* pParams );
void CarBody_printTestCases( CarBody* pCarBody, int eventId, void* pParams ){
    MainTop_printTestCases( pCarBody, &pCarBody->mainStm, eventId, pParams );
}
static void SharedTop_forEachHsmStateCombination( CarBody* pContext, SharedTop* pUsm, HsmStates** hsmStates, int depth, void (*callback)(CarBody*, SharedTop*, HsmStates**) ) {
    if (hsmStates[depth] == NULL) {
        callback(pContext, pUsm, hsmStates);
        return;
    }
    HsmStates* entry = hsmStates[depth];
    for (int i = 0; entry->arrStates[i] != STATE_UNDEF; i++) {
        entry->currentState = entry->arrStates[i];
        SharedTop_forEachHsmStateCombination(pContext, pUsm, hsmStates, depth + 1, callback);
    }
}
static uint64_t SharedStmHsm_States[] = { SharedTop_Charge, SharedTop_Drain, SharedTop_InitPt, SharedTop_Discharging, SharedTop_Charging, SharedTop_Idle, SharedTop_Discharge, STATE_UNDEF };

static void SharedTop_printCombination( CarBody* pContext, SharedTop* pUsm, HsmStates** hsmStates ) {
    extern HsmStates** g_activeHsmStates;
    g_activeHsmStates = hsmStates;
    int i = 0;
    while( hsmStates[ i ] != NULL ) {
        HdStateMachine* pHsm = hsmStates[ i ]->pHsm;
        pHsm->nCurrentState = hsmStates[ i ]->currentState;
        pHsm->nPseudostate = hsmStates[ i ]->currentState;
        i++;
    }
    if( !isRedundantPattern( hsmStates ) ){
        if( SharedTop_EventProc( pContext, pUsm, g_eventId, g_pParams ) ){
            addPattern( hsmStates );
            i = 0;
            while( hsmStates[ i ] != NULL ) {
                HdStateMachine* pHsm = hsmStates[ i ]->pHsm;
                if( pHsm->bHandled || hsmStates[ i ]->wasQueried ){
                    printf( "%20s ", SharedTop_State_toString( pUsm, pHsm, hsmStates[ i ]->currentState ) );
                }else {
                    printf( "%20s ", "Dont't care");
                }
                i++;
            }
            printf( "\n" );
        }
    }
    g_activeHsmStates = NULL; // cleanup
}
static void SharedTop_printTestCases( CarBody* pContext, SharedTop* pUsm, int eventId, void* pParams ) {
    HsmStates* hsmStates[] = {                                  // NULL-terminated list of HSMs
        &( HsmStates ){ .pEventProc = SharedStmHsm_EventProc, .pHsm = &pUsm->SharedStmHsm, .arrStates = SharedStmHsm_States }, 
        NULL
    };
    g_eventId = eventId;
    g_pParams = pParams;
    SharedTop_forEachHsmStateCombination( pContext, pUsm, hsmStates, 0, SharedTop_printCombination );
    freeHandledPatterns();
}
static void MainTop_forEachHsmStateCombination( CarBody* pContext, MainTop* pUsm, HsmStates** hsmStates, int depth, void (*callback)(CarBody*, MainTop*, HsmStates**) ) {
    if (hsmStates[depth] == NULL) {
        callback(pContext, pUsm, hsmStates);
        return;
    }
    HsmStates* entry = hsmStates[depth];
    for (int i = 0; entry->arrStates[i] != STATE_UNDEF; i++) {
        entry->currentState = entry->arrStates[i];
        MainTop_forEachHsmStateCombination(pContext, pUsm, hsmStates, depth + 1, callback);
    }
}
static uint64_t DrivingRgn1Hsm_States[] = { MainTop_DrivingRgn1Init, MainTop_SeatBeltsFastened, MainTop_SeatBeltsUnfastened, MainTop_SeatBeltInit, MainTop_SeatBeltsTighten, STATE_UNDEF };
static uint64_t DrivingRgn2Hsm_States[] = { MainTop_AirbagArmed, MainTop_AirbagDeployed, MainTop_AirbagInit, STATE_UNDEF };
static uint64_t DrivingRgn3Hsm_States[] = { MainTop_CollisionDetectHit, MainTop_CollisionDetectAlert, MainTop_CollisionDetectClear, MainTop_CollisionDetectInit, STATE_UNDEF };
static uint64_t CarOnRgn1Hsm_States[] = { MainTop_EngineIdle, MainTop_EngineAccel, MainTop_EngineDeccel, MainTop_EngineMgmtInit, MainTop_CarOnRgn1Init, STATE_UNDEF };
static uint64_t CarOnRgn2Hsm_States[] = { MainTop_MainBattery, MainTop_BatteryMgmtInit, STATE_UNDEF };
static uint64_t AdaptiveSystemRgn1Hsm_States[] = { MainTop_InfotainmentAV, MainTop_InfotainmentInit, MainTop_InfotainmentNavi, MainTop_InfotainmentOff, STATE_UNDEF };
static uint64_t CarOnRgn3Hsm_States[] = { MainTop_ClimateCtrlOff, MainTop_ClimateCtrlMan, MainTop_ClimateCtrlAuto, MainTop_ClimateCtrlInit, MainTop_AdaptiveSystemInit, STATE_UNDEF };
static uint64_t MainStmHsm_States[] = { MainTop_CarOff, MainTop_MainInit, MainTop_Parked, MainTop_Neutral, MainTop_GearInit, MainTop_Reversed, MainTop_Drive, MainTop_CarOnInit, STATE_UNDEF };

static void MainTop_printCombination( CarBody* pContext, MainTop* pUsm, HsmStates** hsmStates ) {
    if( isRedundantPattern( hsmStates ) ){
        return;
    }
    extern HsmStates** g_activeHsmStates;
    g_activeHsmStates = hsmStates;
    int i = 0;
    while( hsmStates[ i ] != NULL ) {
        HdStateMachine* pHsm = hsmStates[ i ]->pHsm;
        pHsm->nCurrentState = hsmStates[ i ]->currentState;
        pHsm->nPseudostate = hsmStates[ i ]->currentState;
        i++;
    }
    //MainTop_StateDefaultTrans( pContext, pUsm );
    char logBuf[ 1024 ] = "";
    i = 0;
    while( hsmStates[ i ] != NULL ) {
        char _logBuf[ 255 ];
        HdStateMachine* pHsm = hsmStates[ i ]->pHsm;
        sprintf( _logBuf, "%20s ", MainTop_State_toString( pUsm, pHsm, hsmStates[ i ]->currentState ) );
        strcat( logBuf, _logBuf );
        i++;
    }
    strcat( logBuf, "\n" );
    if( MainTop_EventProc( pContext, pUsm, g_eventId, g_pParams ) ){
        MainTop_StateDefaultTrans( pContext, pUsm );
        addPattern( hsmStates );
        printf( logBuf );
        i = 0;
        while( hsmStates[ i ] != NULL ) {
            HdStateMachine* pHsm = hsmStates[ i ]->pHsm;
            if( pHsm->bHandled || hsmStates[ i ]->wasQueried ){
                printf( "%20s ", MainTop_State_toString( pUsm, pHsm, pHsm->nCurrentState ) );
            }else {
                printf( "%20s ", "Dont't care");
            }
            i++;
        }
        printf( "\n" );
    }
    g_activeHsmStates = NULL; // cleanup
}
static void MainTop_printTestCases( CarBody* pContext, MainTop* pUsm, int eventId, void* pParams ) {
    HsmStates* hsmStates[] = {                                  // NULL-terminated list of HSMs
        &( HsmStates ){ .name = "DrivingRgn1Hsm", .pEventProc = DrivingRgn1Hsm_EventProc, .pHsm = &pUsm->DrivingRgn1Hsm, .arrStates = DrivingRgn1Hsm_States }, 
        &( HsmStates ){ .name = "DrivingRgn2Hsm", .pEventProc = DrivingRgn2Hsm_EventProc, .pHsm = &pUsm->DrivingRgn2Hsm, .arrStates = DrivingRgn2Hsm_States }, 
        &( HsmStates ){ .name = "DrivingRgn3Hsm", .pEventProc = DrivingRgn3Hsm_EventProc, .pHsm = &pUsm->DrivingRgn3Hsm, .arrStates = DrivingRgn3Hsm_States }, 
        &( HsmStates ){ .name = "CarOnRgn1Hsm", .pEventProc = CarOnRgn1Hsm_EventProc, .pHsm = &pUsm->CarOnRgn1Hsm, .arrStates = CarOnRgn1Hsm_States }, 
        &( HsmStates ){ .name = "CarOnRgn2Hsm", .pEventProc = CarOnRgn2Hsm_EventProc, .pHsm = &pUsm->CarOnRgn2Hsm, .arrStates = CarOnRgn2Hsm_States }, /* SharedTop_StateDefaultTrans( pCarBody, &pUsm->MainBatteryHsm ) */
        &( HsmStates ){ .name = "AdaptiveSystemRgn1Hsm", .pEventProc = AdaptiveSystemRgn1Hsm_EventProc, .pHsm = &pUsm->AdaptiveSystemRgn1Hsm, .arrStates = AdaptiveSystemRgn1Hsm_States }, 
        &( HsmStates ){ .name = "CarOnRgn3Hsm", .pEventProc = CarOnRgn3Hsm_EventProc, .pHsm = &pUsm->CarOnRgn3Hsm, .arrStates = CarOnRgn3Hsm_States }, 
        &( HsmStates ){ .name = "MainStmHsm", .pEventProc = MainStmHsm_EventProc, .pHsm = &pUsm->MainStmHsm, .arrStates = MainStmHsm_States }, 
        NULL
    };
    int i = 0;
    while( hsmStates[ i ] != NULL ) {
        printf( "%20s ", hsmStates[ i ]->name );
        i++;
    }
    printf( "\n");
    g_eventId = eventId;
    g_pParams = pParams;
    MainTop_forEachHsmStateCombination( pContext, pUsm, hsmStates, 0, MainTop_printCombination );
    freeHandledPatterns();
}
