/* File generated by Đức's ClasHStamP */
#define __CarBody_INTERNAL__
#include "CommonInclude.h"
#include "CarBody.h"
#include "ObjsBuilder.h"                                        
/** @private @static @memberof CarBody */
static int gVar = 1;                                            
/** @private @static @memberof CarBody */
static int x = 2;                                               
/** @private @static @memberof CarBody */
static int y = 3;                                               
/** @public @memberof CarBody */
void CarBody_moveRight(
    CarBody* pCarBody
){
} /* CarBody_moveRight */

/** @public @memberof CarBody */
void CarBody_moveLeft(
    CarBody* pCarBody
){
} /* CarBody_moveLeft */

/** @public @memberof CarBody */
void CarBody_turnOff(
    CarBody* pCarBody
){
    ImgSprite_setBrightness((ImgSprite*)display, 0);
    ImgSprite_setBrightness((ImgSprite*)batteryOper, 0);
    ImgSprite_setBrightness((ImgSprite*)speedometer, 0);
    ImgSprite_setBrightness((ImgSprite*)radar, 0);
    ImgSprite_setBrightness((ImgSprite*)seatbelt, 0);
    ImgSprite_setBrightness((ImgSprite*)airbag, 0);
    ImgSprite_setBrightness((ImgSprite*)fanCtrl, 0);
    ImgSprite_setBrightness((ImgSprite*)gear, 0);
} /* CarBody_turnOff */

/** @public @memberof CarBody */
void CarBody_turnOn(
    CarBody* pCarBody
){
    ImgSprite_setBrightness((ImgSprite*)display, 1);
    ImgSprite_setBrightness((ImgSprite*)batteryOper, 1);
    ImgSprite_setBrightness((ImgSprite*)speedometer, 1);
    ImgSprite_setBrightness((ImgSprite*)radar, 1);
    ImgSprite_setBrightness((ImgSprite*)seatbelt, 1);
    ImgSprite_setBrightness((ImgSprite*)airbag, 1);
    ImgSprite_setBrightness((ImgSprite*)fanCtrl, 1);
    ImgSprite_setBrightness((ImgSprite*)gear, 1);
} /* CarBody_turnOn */

const TCHAR* CarBodyEvent_toString( CarBody_EVENT value ){
    switch( value ){
    case CarBody_ACCEL_PRESSED: return _T( "ACCEL_PRESSED" );
    case CarBody_ACCEL_RELEASED: return _T( "ACCEL_RELEASED" );
    case CarBody_GEAR_DOWN: return _T( "GEAR_DOWN" );
    case CarBody_GEAR_UP: return _T( "GEAR_UP" );
    case CarBody_PWR_BTN: return _T( "PWR_BTN" );
    case CarBody_REVERSE: return _T( "REVERSE" );
    default: return _T( "CarBody_UNKNOWN" );
    }
}
static BOOL MainTop_Reset( CarBody* pCarBody, MainTop* pUsm, STM_RESET* pResetParams );
static void MainTop_Prepare( MainTop* pUsm, HdStateMachine* pParent );
static BOOL MainTop_EventProc( CarBody* pCarBody, MainTop* pUsm, CarBody_EVENT nEventId, void* pEventParams );
static BOOL MainTop_StateDefaultTrans( CarBody* pCarBody, MainTop* pUsm );
BOOL CarBody_Start( CarBody* pCarBody ){
    MainTop_Prepare( &pCarBody->mainStm, NULL );
    BOOL bResult = MainTop_Reset( pCarBody, &pCarBody->mainStm, NULL );
    bResult |= MainTop_StateDefaultTrans( pCarBody, &pCarBody->mainStm );
    return bResult;
}
BOOL CarBody_EventProc( CarBody* pCarBody, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = MainTop_EventProc( pCarBody, &pCarBody->mainStm, nEventId, pEventParams );
    bResult |= MainTop_StateDefaultTrans( pCarBody, &pCarBody->mainStm );
    return bResult;
}

/**
 * Implementation for Statemachine: MainTop
 */
const TCHAR* MainTop_State_toString( MainTop* pUsm, HdStateMachine* pHsm, uint64_t nState ){
    TCHAR* sState;
    if( pHsm == &pUsm->CarOnRgn1Hsm ){
        switch( nState ){
        case MainTop_Reversed                   : sState = "Reversed"; break;
        case MainTop_Drive                      : sState = "Drive"; break;
        case MainTop_GearEngaged                : sState = "GearEngaged"; break;
        case MainTop_GearInit                   : sState = "GearInit"; break;
        case MainTop_Neutral                    : sState = "Neutral"; break;
        case MainTop_Parked                     : sState = "Parked"; break;
        case MainTop_CarOnRgn1                  : sState = "CarOnRgn1"; break;
        default                                 : sState = "CarOnRgn1_OutOfRange"; break;
        }
    }else if( pHsm == &pUsm->CarOnRgn2Hsm ){
        switch( nState ){
        case MainTop_InfotainmentInit           : sState = "InfotainmentInit"; break;
        case MainTop_BackCamera                 : sState = "BackCamera"; break;
        case MainTop_DisplayAvail               : sState = "DisplayAvail"; break;
        case MainTop_CarOnRgn2                  : sState = "CarOnRgn2"; break;
        default                                 : sState = "CarOnRgn2_OutOfRange"; break;
        }
    }else if( pHsm == &pUsm->MainStmHsm ){
        switch( nState ){
        case MainTop_CarOnRgn1Init              : sState = "CarOnRgn1Init"; break;
        case MainTop_EngineIdle                 : sState = "EngineIdle"; break;
        case MainTop_EngineAccel                : sState = "EngineAccel"; break;
        case MainTop_EngineDeccel               : sState = "EngineDeccel"; break;
        case MainTop_EngineMgmtInit             : sState = "EngineMgmtInit"; break;
        case MainTop_EngineManagement           : sState = "EngineManagement"; break;
        case MainTop_CarOn                      : sState = "CarOn"; break;
        case MainTop_CarOff                     : sState = "CarOff"; break;
        case MainTop_MainInit                   : sState = "MainInit"; break;
        case MainTop_MainStm                    : sState = "MainStm"; break;
        default                                 : sState = "MainStm_OutOfRange"; break;
        }
    }else { 
        sState = "UnknownState";
    }
    return sState;
}
static void MainStmHsm_BgnTrans( CarBody *pCarBody, HdStateMachine* pStm, uint64_t targetState );
static void MainStmHsm_EndTrans( CarBody *pCarBody, HdStateMachine* pStm );
static BOOL MainStmHsm_Abort( CarBody* pCarBody, HdStateMachine* pStm );
static BOOL MainStmHsm_Reset( CarBody* pCarBody, HdStateMachine* pStm, STM_RESET* pResetParams );
static BOOL MainStmHsm_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams );
static void CarOnRgn1Hsm_BgnTrans( CarBody *pCarBody, HdStateMachine* pStm, uint64_t targetState );
static void CarOnRgn1Hsm_EndTrans( CarBody *pCarBody, HdStateMachine* pStm );
static BOOL CarOnRgn1Hsm_Abort( CarBody* pCarBody, HdStateMachine* pStm );
static BOOL CarOnRgn1Hsm_Reset( CarBody* pCarBody, HdStateMachine* pStm, STM_RESET* pResetParams );
static BOOL CarOnRgn1Hsm_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams );
static void CarOnRgn2Hsm_BgnTrans( CarBody *pCarBody, HdStateMachine* pStm, uint64_t targetState );
static void CarOnRgn2Hsm_EndTrans( CarBody *pCarBody, HdStateMachine* pStm );
static BOOL CarOnRgn2Hsm_Abort( CarBody* pCarBody, HdStateMachine* pStm );
static BOOL CarOnRgn2Hsm_Reset( CarBody* pCarBody, HdStateMachine* pStm, STM_RESET* pResetParams );
static BOOL CarOnRgn2Hsm_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams );
static void MainTop_CarOnRgn1_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_CarOnRgn1 ) ){
        if( !( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainTop_CarOnRgn1 ){
            pStm->nPseudostate = MainTop_GearInit;
        }
        if ( ( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering ) {
            pStm->nPseudostate = pStm->lastEnteredState;
        }
    }
}
static BOOL MainTop_CarOnRgn1_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_CarOnRgn1;
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return pStm->bHandled;
}
static void MainTop_CarOnRgn1_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_CarOnRgn1 ) ){ 
    }
}
static void MainTop_GearEngaged_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_GearEngaged ) ){
        MainTop_CarOnRgn1_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	1301	-60	373	144	727	-460	1215	794	GearEngaged" );
    }
}
static BOOL MainTop_GearEngaged_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_GearEngaged;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	1301	-60	373	144	727	-460	1215	794	GearEngaged" );
        switch( nEventId ){
        case CarBody_GEAR_DOWN:{
            CarOnRgn1Hsm_BgnTrans( pCarBody, pStm, MainTop_Neutral );
            MainStmHsm_Reset( pCarBody, &( ( MainTop* )pStm->pMain )->MainStmHsm, &( STM_RESET ){ .entryPt = MainTop_EngineIdle } );
            CarOnRgn2Hsm_Reset( pCarBody, &( ( MainTop* )pStm->pMain )->CarOnRgn2Hsm, &( STM_RESET ){ .entryPt = MainTop_DisplayAvail } );
            CarOnRgn1Hsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_CarOnRgn1_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_GearEngaged_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_GearEngaged ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	1301	-60	373	144	727	-460	1215	794	GearEngaged" );
        MainTop_CarOnRgn1_Exit( pCarBody, pStm );
    }
}
static void MainTop_Reversed_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_Reversed ) ){
        MainTop_GearEngaged_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	1345	-10	117	84	727	-460	1215	794	Reversed" );
        ImgSprite_setSpriteCoords(gear, 2, 0);
    }
}
static BOOL MainTop_Reversed_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_Reversed;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	1345	-10	117	84	727	-460	1215	794	Reversed" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_GearEngaged_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_Reversed_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_Reversed ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	1345	-10	117	84	727	-460	1215	794	Reversed" );
        MainTop_GearEngaged_Exit( pCarBody, pStm );
    }
}
static void MainTop_Drive_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_Drive ) ){
        MainTop_GearEngaged_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	1541	-10	117	84	727	-460	1215	794	Drive" );
        ImgSprite_setSpriteCoords(gear, 3, 0);
    }
}
static BOOL MainTop_Drive_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_Drive;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	1541	-10	117	84	727	-460	1215	794	Drive" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_GearEngaged_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_Drive_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_Drive ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	1541	-10	117	84	727	-460	1215	794	Drive" );
        MainTop_GearEngaged_Exit( pCarBody, pStm );
    }
}
static void MainTop_Neutral_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_Neutral ) ){
        MainTop_CarOnRgn1_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	1345	-186	117	84	727	-460	1215	794	Neutral" );
        ImgSprite_setSpriteCoords(gear, 1, 0);
    }
}
static BOOL MainTop_Neutral_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_Neutral;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	1345	-186	117	84	727	-460	1215	794	Neutral" );
        switch( nEventId ){
        case CarBody_GEAR_UP:{
            CarOnRgn1Hsm_BgnTrans( pCarBody, pStm, MainTop_Drive );
            CarOnRgn1Hsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        } break;
        case CarBody_GEAR_DOWN:{
            CarOnRgn1Hsm_BgnTrans( pCarBody, pStm, MainTop_Parked );
            CarOnRgn1Hsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        } break;
        case CarBody_REVERSE:{
            CarOnRgn1Hsm_BgnTrans( pCarBody, pStm, MainTop_Reversed );
            CarOnRgn2Hsm_Reset( pCarBody, &( ( MainTop* )pStm->pMain )->CarOnRgn2Hsm, &( STM_RESET ){ .entryPt = MainTop_BackCamera } );
            CarOnRgn1Hsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_CarOnRgn1_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_Neutral_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_Neutral ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	1345	-186	117	84	727	-460	1215	794	Neutral" );
        MainTop_CarOnRgn1_Exit( pCarBody, pStm );
    }
}
static void MainTop_Parked_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_Parked ) ){
        MainTop_CarOnRgn1_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	1138	-105	117	84	727	-460	1215	794	Parked" );
        ImgSprite_setSpriteCoords(gear, 0, 0);
    }
}
static BOOL MainTop_Parked_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_Parked;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	1138	-105	117	84	727	-460	1215	794	Parked" );
        switch( nEventId ){
        case CarBody_GEAR_UP:{
            CarOnRgn1Hsm_BgnTrans( pCarBody, pStm, MainTop_Neutral );
            CarOnRgn1Hsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_CarOnRgn1_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_Parked_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_Parked ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	1138	-105	117	84	727	-460	1215	794	Parked" );
        MainTop_CarOnRgn1_Exit( pCarBody, pStm );
    }
}
static void CarOnRgn1Hsm_BgnTrans( CarBody *pCarBody, HdStateMachine* pStm, uint64_t targetState ){
    pStm->nTargetState = targetState;
    pStm->nPseudostate = targetState;
    switch( pStm->nCurrentState ){
    case MainTop_CarOnRgn1:     MainTop_CarOnRgn1_Exit( pCarBody, pStm ); break;
    case MainTop_Reversed:      MainTop_Reversed_Exit( pCarBody, pStm ); break;
    case MainTop_Drive:         MainTop_Drive_Exit( pCarBody, pStm ); break;
    case MainTop_GearEngaged:   MainTop_GearEngaged_Exit( pCarBody, pStm ); break;
    case MainTop_Neutral:       MainTop_Neutral_Exit( pCarBody, pStm ); break;
    case MainTop_Parked:        MainTop_Parked_Exit( pCarBody, pStm ); break;
    default: break;
    }
}
static BOOL CarOnRgn1Hsm_Reset( CarBody* pCarBody, HdStateMachine* pStm, STM_RESET* pResetParams ) {
    if( pResetParams != NULL && pResetParams->entryPt != STATE_UNDEF ){
        HdStateMachine_Req( pStm, pResetParams->entryPt );
        return FALSE;
    }
    pStm->nPseudostate = MainTop_CarOnRgn1;
    pStm->bIsExternTrans = TRUE;
    pStm->nDepth = ( pResetParams != NULL ? pResetParams->nDepth + 1 : 0 );
    CarOnRgn1Hsm_BgnTrans( pCarBody, pStm, pStm->nPseudostate );
    CarOnRgn1Hsm_EndTrans( pCarBody, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static BOOL CarOnRgn1Hsm_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nLCAState = STATE_UNDEF;
    pStm->bHandled = FALSE;
    pStm->wasHandled = FALSE;
    switch( pStm->nCurrentState ){
    case MainTop_CarOnRgn1:                     bResult |= MainTop_CarOnRgn1_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_Reversed:                      bResult |= MainTop_Reversed_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_Drive:                         bResult |= MainTop_Drive_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_GearEngaged:                   bResult |= MainTop_GearEngaged_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_Neutral:                       bResult |= MainTop_Neutral_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_Parked:                        bResult |= MainTop_Parked_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    default: break;
    }
    return bResult;
}
static BOOL CarOnRgn1Hsm_Abort( CarBody* pCarBody, HdStateMachine* pStm ) {
    pStm->nSourceState = MainTop_CarOnRgn1;
    CarOnRgn1Hsm_BgnTrans( pCarBody, pStm, STATE_UNDEF );
    CarOnRgn1Hsm_EndTrans( pCarBody, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static void CarOnRgn1Hsm_EndTrans( CarBody *pCarBody, HdStateMachine* pStm ){
    pStm->nCurrentState = pStm->nTargetState;
    pStm->bIsExternTrans = FALSE;
    switch( pStm->nCurrentState ){
    case MainTop_CarOnRgn1:     MainTop_CarOnRgn1_Entry( pCarBody, pStm ); break;
    case MainTop_Reversed:      MainTop_Reversed_Entry( pCarBody, pStm ); break;
    case MainTop_Drive:         MainTop_Drive_Entry( pCarBody, pStm ); break;
    case MainTop_GearEngaged:   MainTop_GearEngaged_Entry( pCarBody, pStm ); break;
    case MainTop_Neutral:       MainTop_Neutral_Entry( pCarBody, pStm ); break;
    case MainTop_Parked:        MainTop_Parked_Entry( pCarBody, pStm ); break;
    default: break;
    }
}
static BOOL CarOnRgn1Hsm_StateDefaultTrans( CarBody* pCarBody, HdStateMachine* pStm ){
    BOOL bResult = FALSE;
    pStm->nSourceState = pStm->nCurrentState;
    pStm->nLCAState = STATE_UNDEF;
        if ( pStm->nPseudostate == MainTop_GearInit  ) {
            CarOnRgn1Hsm_BgnTrans( pCarBody, pStm, MainTop_Parked );
            CarOnRgn1Hsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        }else if( pStm->nCurrentState != pStm->nPseudostate ){
            CarOnRgn1Hsm_BgnTrans( pCarBody, pStm, pStm->nPseudostate );
            CarOnRgn1Hsm_EndTrans( pCarBody, pStm );
            bResult = TRUE;
        }else{
        }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    ( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering = FALSE;
    return bResult;
}
static void MainTop_CarOnRgn2_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_CarOnRgn2 ) ){
        if( !( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainTop_CarOnRgn2 ){
            pStm->nPseudostate = MainTop_InfotainmentInit;
        }
        if ( ( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering ) {
            pStm->nPseudostate = pStm->lastEnteredState;
        }
    }
}
static BOOL MainTop_CarOnRgn2_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_CarOnRgn2;
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return pStm->bHandled;
}
static void MainTop_CarOnRgn2_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_CarOnRgn2 ) ){ 
    }
}
static void MainTop_BackCamera_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_BackCamera ) ){
        MainTop_CarOnRgn2_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	1767	61	124	63	727	-460	1215	794	BackCamera" );
        ImgSprite_setSpriteCoords(display, 0, 1);
    }
}
static BOOL MainTop_BackCamera_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_BackCamera;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	1767	61	124	63	727	-460	1215	794	BackCamera" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_CarOnRgn2_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_BackCamera_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_BackCamera ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	1767	61	124	63	727	-460	1215	794	BackCamera" );
        MainTop_CarOnRgn2_Exit( pCarBody, pStm );
    }
}
static void MainTop_DisplayAvail_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_DisplayAvail ) ){
        MainTop_CarOnRgn2_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	1767	-73	124	63	727	-460	1215	794	DisplayAvail" );
        ImgSprite_setSpriteCoords(display, 1, 1);
    }
}
static BOOL MainTop_DisplayAvail_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_DisplayAvail;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	1767	-73	124	63	727	-460	1215	794	DisplayAvail" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_CarOnRgn2_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_DisplayAvail_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_DisplayAvail ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	1767	-73	124	63	727	-460	1215	794	DisplayAvail" );
        MainTop_CarOnRgn2_Exit( pCarBody, pStm );
    }
}
static void CarOnRgn2Hsm_BgnTrans( CarBody *pCarBody, HdStateMachine* pStm, uint64_t targetState ){
    pStm->nTargetState = targetState;
    pStm->nPseudostate = targetState;
    switch( pStm->nCurrentState ){
    case MainTop_CarOnRgn2:     MainTop_CarOnRgn2_Exit( pCarBody, pStm ); break;
    case MainTop_BackCamera:    MainTop_BackCamera_Exit( pCarBody, pStm ); break;
    case MainTop_DisplayAvail:  MainTop_DisplayAvail_Exit( pCarBody, pStm ); break;
    default: break;
    }
}
static BOOL CarOnRgn2Hsm_Reset( CarBody* pCarBody, HdStateMachine* pStm, STM_RESET* pResetParams ) {
    if( pResetParams != NULL && pResetParams->entryPt != STATE_UNDEF ){
        HdStateMachine_Req( pStm, pResetParams->entryPt );
        return FALSE;
    }
    pStm->nPseudostate = MainTop_CarOnRgn2;
    pStm->bIsExternTrans = TRUE;
    pStm->nDepth = ( pResetParams != NULL ? pResetParams->nDepth + 1 : 0 );
    CarOnRgn2Hsm_BgnTrans( pCarBody, pStm, pStm->nPseudostate );
    CarOnRgn2Hsm_EndTrans( pCarBody, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static BOOL CarOnRgn2Hsm_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nLCAState = STATE_UNDEF;
    pStm->bHandled = FALSE;
    pStm->wasHandled = FALSE;
    switch( pStm->nCurrentState ){
    case MainTop_CarOnRgn2:                     bResult |= MainTop_CarOnRgn2_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_BackCamera:                    bResult |= MainTop_BackCamera_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_DisplayAvail:                  bResult |= MainTop_DisplayAvail_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    default: break;
    }
    return bResult;
}
static BOOL CarOnRgn2Hsm_Abort( CarBody* pCarBody, HdStateMachine* pStm ) {
    pStm->nSourceState = MainTop_CarOnRgn2;
    CarOnRgn2Hsm_BgnTrans( pCarBody, pStm, STATE_UNDEF );
    CarOnRgn2Hsm_EndTrans( pCarBody, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static void CarOnRgn2Hsm_EndTrans( CarBody *pCarBody, HdStateMachine* pStm ){
    pStm->nCurrentState = pStm->nTargetState;
    pStm->bIsExternTrans = FALSE;
    switch( pStm->nCurrentState ){
    case MainTop_CarOnRgn2:     MainTop_CarOnRgn2_Entry( pCarBody, pStm ); break;
    case MainTop_BackCamera:    MainTop_BackCamera_Entry( pCarBody, pStm ); break;
    case MainTop_DisplayAvail:  MainTop_DisplayAvail_Entry( pCarBody, pStm ); break;
    default: break;
    }
}
static BOOL CarOnRgn2Hsm_StateDefaultTrans( CarBody* pCarBody, HdStateMachine* pStm ){
    BOOL bResult = FALSE;
    pStm->nSourceState = pStm->nCurrentState;
    pStm->nLCAState = STATE_UNDEF;
        if ( pStm->nPseudostate == MainTop_InfotainmentInit  ) {
            CarOnRgn2Hsm_BgnTrans( pCarBody, pStm, MainTop_DisplayAvail );
            CarOnRgn2Hsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        }else if( pStm->nCurrentState != pStm->nPseudostate ){
            CarOnRgn2Hsm_BgnTrans( pCarBody, pStm, pStm->nPseudostate );
            CarOnRgn2Hsm_EndTrans( pCarBody, pStm );
            bResult = TRUE;
        }else{
        }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    ( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering = FALSE;
    return bResult;
}
static void MainTop_MainStm_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_MainStm ) ){
        if( !( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainTop_MainStm ){
            pStm->nPseudostate = MainTop_MainInit;
        }
        if ( ( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering ) {
            pStm->nPseudostate = pStm->lastEnteredState;
        }
    }
}
static BOOL MainTop_MainStm_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_MainStm;
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return pStm->bHandled;
}
static void MainTop_MainStm_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_MainStm ) ){ 
    }
}
static void MainTop_CarOn_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_CarOn ) ){
        MainTop_MainStm_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	767	-313	1150	622	727	-460	1215	794	CarOn" );
        if( !( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainTop_CarOn ){
            pStm->nPseudostate = MainTop_CarOnRgn1Init;
        }
        CarOnRgn1Hsm_Reset( pCarBody, &( ( MainTop* )pStm->pMain )->CarOnRgn1Hsm, &( STM_RESET ){ .nDepth = pStm->nDepth } );
        CarOnRgn2Hsm_Reset( pCarBody, &( ( MainTop* )pStm->pMain )->CarOnRgn2Hsm, &( STM_RESET ){ .nDepth = pStm->nDepth } );
        CarBody_turnOn( pCarBody );
    }
}
static BOOL MainTop_CarOn_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->bHandled |= CarOnRgn1Hsm_EventProc( pCarBody, &( ( MainTop* )pStm->pMain )->CarOnRgn1Hsm, nEventId, pEventParams );
    pStm->bHandled |= CarOnRgn2Hsm_EventProc( pCarBody, &( ( MainTop* )pStm->pMain )->CarOnRgn2Hsm, nEventId, pEventParams );
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_CarOn;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	767	-313	1150	622	727	-460	1215	794	CarOn" );
        switch( nEventId ){
        case CarBody_PWR_BTN:{
            if (HdStateMachine_IsIn( &( ( MainTop* )pStm->pMain )->CarOnRgn1Hsm, MainTop_Parked )) {
                MainStmHsm_BgnTrans( pCarBody, pStm, MainTop_CarOff );
                MainStmHsm_EndTrans( pCarBody, pStm );
                bResult |= TRUE;
            }
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_MainStm_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_CarOn_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_CarOn ) ){ 
        CarOnRgn1Hsm_Abort( pCarBody, &( ( MainTop* )pStm->pMain )->CarOnRgn1Hsm );
        CarOnRgn2Hsm_Abort( pCarBody, &( ( MainTop* )pStm->pMain )->CarOnRgn2Hsm );
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	767	-313	1150	622	727	-460	1215	794	CarOn" );
        MainTop_MainStm_Exit( pCarBody, pStm );
    }
}
static void MainTop_EngineManagement_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_EngineManagement ) ){
        MainTop_CarOn_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	827	-219	217	519	727	-460	1215	794	EngineManagement" );
        if( !( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering && pStm->nTargetState == MainTop_EngineManagement ){
            pStm->nPseudostate = MainTop_EngineMgmtInit;
        }
    }
}
static BOOL MainTop_EngineManagement_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_EngineManagement;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	827	-219	217	519	727	-460	1215	794	EngineManagement" );
        switch( nEventId ){
        case CarBody_ACCEL_PRESSED:{
            if (HdStateMachine_IsIn( &( ( MainTop* )pStm->pMain )->CarOnRgn1Hsm, MainTop_GearEngaged )) {
                MainStmHsm_BgnTrans( pCarBody, pStm, MainTop_EngineAccel );
                MainStmHsm_EndTrans( pCarBody, pStm );
                bResult |= TRUE;
            }
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_CarOn_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_EngineManagement_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_EngineManagement ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	827	-219	217	519	727	-460	1215	794	EngineManagement" );
        MainTop_CarOn_Exit( pCarBody, pStm );
    }
}
static void MainTop_EngineIdle_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_EngineIdle ) ){
        MainTop_EngineManagement_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	843	-151	144	63	727	-460	1215	794	EngineIdle" );
        ImgSprite_setSpriteCoords(speedometer, 1, 0);
    }
}
static BOOL MainTop_EngineIdle_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_EngineIdle;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	843	-151	144	63	727	-460	1215	794	EngineIdle" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_EngineManagement_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_EngineIdle_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_EngineIdle ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	843	-151	144	63	727	-460	1215	794	EngineIdle" );
        MainTop_EngineManagement_Exit( pCarBody, pStm );
    }
}
static void MainTop_EngineAccel_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_EngineAccel ) ){
        MainTop_EngineManagement_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	843	72	117	73	727	-460	1215	794	EngineAccel" );
        ImgSprite_setSpriteCoords(speedometer, 1, 1);
    }
}
static BOOL MainTop_EngineAccel_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_EngineAccel;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	843	72	117	73	727	-460	1215	794	EngineAccel" );
        switch( nEventId ){
        case CarBody_ACCEL_RELEASED:{
            if (HdStateMachine_IsIn( &( ( MainTop* )pStm->pMain )->CarOnRgn1Hsm, MainTop_GearEngaged )) {
                MainStmHsm_BgnTrans( pCarBody, pStm, MainTop_EngineDeccel );
                MainStmHsm_EndTrans( pCarBody, pStm );
                bResult |= TRUE;
            }
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_EngineManagement_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_EngineAccel_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_EngineAccel ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	843	72	117	73	727	-460	1215	794	EngineAccel" );
        MainTop_EngineManagement_Exit( pCarBody, pStm );
    }
}
static void MainTop_EngineDeccel_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_EngineDeccel ) ){
        MainTop_EngineManagement_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	843	188	117	73	727	-460	1215	794	EngineDeccel" );
        ImgSprite_setSpriteCoords(speedometer, 0, 1);
    }
}
static BOOL MainTop_EngineDeccel_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_EngineDeccel;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	843	188	117	73	727	-460	1215	794	EngineDeccel" );
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_EngineManagement_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_EngineDeccel_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_EngineDeccel ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	843	188	117	73	727	-460	1215	794	EngineDeccel" );
        MainTop_EngineManagement_Exit( pCarBody, pStm );
    }
}
static void MainTop_CarOff_Entry( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, MainTop_CarOff ) ){
        MainTop_MainStm_Entry( pCarBody, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pCarBody, "Model/CarBody/MainTop	946	-414	207	51	727	-460	1215	794	CarOff" );
        CarBody_turnOff( pCarBody );
    }
}
static BOOL MainTop_CarOff_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    if( !pStm->bHandled ){
        pStm->nSourceState = MainTop_CarOff;
        HdStateMachine_DefaultDoingAction( pStm, pCarBody, "Model/CarBody/MainTop	946	-414	207	51	727	-460	1215	794	CarOff" );
        switch( nEventId ){
        case CarBody_PWR_BTN:{
            MainStmHsm_BgnTrans( pCarBody, pStm, MainTop_CarOn );
            MainStmHsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        } break;
        default: break;
        }
    }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    return MainTop_MainStm_EventProc( pCarBody, pStm, nEventId, pEventParams );
}
static void MainTop_CarOff_Exit( CarBody* pCarBody, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, MainTop_CarOff ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pCarBody, "Model/CarBody/MainTop	946	-414	207	51	727	-460	1215	794	CarOff" );
        MainTop_MainStm_Exit( pCarBody, pStm );
    }
}
static void MainStmHsm_BgnTrans( CarBody *pCarBody, HdStateMachine* pStm, uint64_t targetState ){
    pStm->nTargetState = targetState;
    pStm->nPseudostate = targetState;
    switch( pStm->nCurrentState ){
    case MainTop_MainStm:       MainTop_MainStm_Exit( pCarBody, pStm ); break;
    case MainTop_EngineIdle:    MainTop_EngineIdle_Exit( pCarBody, pStm ); break;
    case MainTop_EngineAccel:   MainTop_EngineAccel_Exit( pCarBody, pStm ); break;
    case MainTop_EngineDeccel:  MainTop_EngineDeccel_Exit( pCarBody, pStm ); break;
    case MainTop_EngineManagement:MainTop_EngineManagement_Exit( pCarBody, pStm ); break;
    case MainTop_CarOn:         MainTop_CarOn_Exit( pCarBody, pStm ); break;
    case MainTop_CarOff:        MainTop_CarOff_Exit( pCarBody, pStm ); break;
    default: break;
    }
}
static BOOL MainStmHsm_Reset( CarBody* pCarBody, HdStateMachine* pStm, STM_RESET* pResetParams ) {
    if( pResetParams != NULL && pResetParams->entryPt != STATE_UNDEF ){
        HdStateMachine_Req( pStm, pResetParams->entryPt );
        return FALSE;
    }
    pStm->nPseudostate = MainTop_MainStm;
    pStm->bIsExternTrans = TRUE;
    pStm->nDepth = ( pResetParams != NULL ? pResetParams->nDepth + 1 : 0 );
    MainStmHsm_BgnTrans( pCarBody, pStm, pStm->nPseudostate );
    MainStmHsm_EndTrans( pCarBody, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static BOOL MainStmHsm_EventProc( CarBody* pCarBody, HdStateMachine* pStm, CarBody_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nLCAState = STATE_UNDEF;
    pStm->bHandled = FALSE;
    pStm->wasHandled = FALSE;
    switch( pStm->nCurrentState ){
    case MainTop_MainStm:                       bResult |= MainTop_MainStm_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_EngineIdle:                    bResult |= MainTop_EngineIdle_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_EngineAccel:                   bResult |= MainTop_EngineAccel_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_EngineDeccel:                  bResult |= MainTop_EngineDeccel_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_EngineManagement:              bResult |= MainTop_EngineManagement_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_CarOn:                         bResult |= MainTop_CarOn_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    case MainTop_CarOff:                        bResult |= MainTop_CarOff_EventProc( pCarBody, pStm, nEventId, pEventParams ); break;
    default: break;
    }
    return bResult;
}
static BOOL MainStmHsm_Abort( CarBody* pCarBody, HdStateMachine* pStm ) {
    pStm->nSourceState = MainTop_MainStm;
    MainStmHsm_BgnTrans( pCarBody, pStm, STATE_UNDEF );
    MainStmHsm_EndTrans( pCarBody, pStm );
    HdStateMachine_IsIn( pStm, STATE_UNDEF );    // used for testcases generation
    return TRUE;
}
static void MainStmHsm_EndTrans( CarBody *pCarBody, HdStateMachine* pStm ){
    pStm->nCurrentState = pStm->nTargetState;
    pStm->bIsExternTrans = FALSE;
    switch( pStm->nCurrentState ){
    case MainTop_MainStm:       MainTop_MainStm_Entry( pCarBody, pStm ); break;
    case MainTop_EngineIdle:    MainTop_EngineIdle_Entry( pCarBody, pStm ); break;
    case MainTop_EngineAccel:   MainTop_EngineAccel_Entry( pCarBody, pStm ); break;
    case MainTop_EngineDeccel:  MainTop_EngineDeccel_Entry( pCarBody, pStm ); break;
    case MainTop_EngineManagement:MainTop_EngineManagement_Entry( pCarBody, pStm ); break;
    case MainTop_CarOn:         MainTop_CarOn_Entry( pCarBody, pStm ); break;
    case MainTop_CarOff:        MainTop_CarOff_Entry( pCarBody, pStm ); break;
    default: break;
    }
}
static BOOL MainStmHsm_StateDefaultTrans( CarBody* pCarBody, HdStateMachine* pStm ){
    BOOL bResult = FALSE;
    pStm->nSourceState = pStm->nCurrentState;
    pStm->nLCAState = STATE_UNDEF;
        if ( pStm->nPseudostate == MainTop_EngineMgmtInit  ) {
            MainStmHsm_BgnTrans( pCarBody, pStm, MainTop_EngineIdle );
            MainStmHsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        } else if ( pStm->nPseudostate == MainTop_CarOnRgn1Init  ) {
            MainStmHsm_BgnTrans( pCarBody, pStm, MainTop_EngineManagement );
            MainStmHsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        } else if ( pStm->nPseudostate == MainTop_MainInit  ) {
            MainStmHsm_BgnTrans( pCarBody, pStm, MainTop_CarOff );
            MainStmHsm_EndTrans( pCarBody, pStm );
            bResult |= TRUE;
        }else if( pStm->nCurrentState != pStm->nPseudostate ){
            MainStmHsm_BgnTrans( pCarBody, pStm, pStm->nPseudostate );
            MainStmHsm_EndTrans( pCarBody, pStm );
            bResult = TRUE;
        }else{
        }
    pStm->bHandled |= bResult;
    pStm->wasHandled |= bResult;
    ( ( MainTop* )pStm->pMain )->lastEnteredStateRecovering = FALSE;
    return bResult;
}
static BOOL MainTop_EventProc( CarBody* pCarBody, MainTop* pUsm, CarBody_EVENT nEventId, void* pEventParams ){
    return MainStmHsm_EventProc( pCarBody, &pUsm->MainStmHsm, nEventId, pEventParams );
}
static BOOL MainTop_StateDefaultTrans( CarBody* pCarBody, MainTop* pUsm ){
    BOOL bResult;
    while( TRUE ){
        bResult = FALSE;
        bResult |= CarOnRgn1Hsm_StateDefaultTrans( pCarBody, &pUsm->CarOnRgn1Hsm );
        bResult |= CarOnRgn2Hsm_StateDefaultTrans( pCarBody, &pUsm->CarOnRgn2Hsm );
        bResult |= MainStmHsm_StateDefaultTrans( pCarBody, &pUsm->MainStmHsm );
        if( bResult == FALSE ){
            break;
        }
    }
    return bResult;
}
static BOOL MainTop_Reset( CarBody* pCarBody, MainTop* pUsm, STM_RESET* pResetParams ){
    pUsm->lastEnteredStateRecovering = ( pResetParams != NULL ? pResetParams->lastEnteredStateRecovering : FALSE );
    MainStmHsm_Abort( pCarBody, &pUsm->MainStmHsm );
    return MainStmHsm_Reset( pCarBody, &pUsm->MainStmHsm, pResetParams );
}
static BOOL MainTop_Abort( CarBody* pCarBody, MainTop* pUsm ){
    return MainStmHsm_Abort( pCarBody, &pUsm->MainStmHsm );
}
static BOOL MainTop_IsFinished( MainTop* pUsm ){
    return pUsm->MainStmHsm.nPseudostate == MainTop_MainStm;
}

static void MainTop_Prepare( MainTop* pUsm, HdStateMachine* pParent ){
    pUsm->pParentStm = pParent;
    pUsm->MainStmHsm.pMain = pUsm;
    pUsm->CarOnRgn1Hsm.pMain = pUsm;
    pUsm->CarOnRgn2Hsm.pMain = pUsm;
}
ImgSprite* CarBody_Copy( CarBody* pCarBody, const CarBody* pSource ){
    ImgSprite_Copy( ( ImgSprite* )pCarBody, ( ImgSprite* )pSource );
    pCarBody->x0 = pSource->x0;
    return ( Sprite* )pCarBody;
}
