/* File generated by Đức's ClasHStamP */
#define __FlexButton_INTERNAL__
#include "CommonInclude.h"
#include "FlexButton.h"
/** @public @memberof FlexButton */
static bool FlexButton_load(
    Sprite* pSprite,
    SDL_Renderer* renderer
){
    FlexButton* pFlexButton = (FlexButton*)pSprite;
    // Get the size of the renderer
    int width, height;
    if ( SDL_GetRendererOutputSize(renderer, &width, &height) != 0 ) {
        printf("Error getting renderer size: %s\n", SDL_GetError());
    }

    pFlexButton->m_rect = (SDL_Rect){
        pFlexButton->m_iniRect.x * width,
        pFlexButton->m_iniRect.y * height,
        pFlexButton->m_iniRect.w * width,
        pFlexButton->m_iniRect.h * height
    };

    FlexButton_Start(pFlexButton);
    return true;
} /* FlexButton_load */

/** @public @memberof FlexButton */
static void FlexButton_draw0(
    Sprite* pSprite,
    SDL_Renderer* renderer
){
    FlexButton* pFlexButton = (FlexButton*)pSprite;
    FlexButton_EventProc(pFlexButton, FlexButton_DRAW0, renderer);
} /* FlexButton_draw0 */

/** @public @memberof FlexButton */
static void FlexButton_draw1(
    Sprite* pSprite,
    SDL_Renderer* renderer
){
    FlexButton* pFlexButton = (FlexButton*)pSprite;
    FlexButton_EventProc(pFlexButton, FlexButton_DRAW1, renderer);
} /* FlexButton_draw1 */

/** @public @memberof FlexButton */
static void FlexButton_updateMouseState(
    Sprite* pSprite,
    int x,
    int y,
    int mouseEvent
){
    FlexButton* pFlexButton = (FlexButton*)pSprite;
    FlexButton* sprite = pFlexButton;
    int mouseX = x;
    int mouseY = y;
    EventListener* pCurListener = sprite->m_mouseListeners;
    MouseEventParams mouseEventParams = { .pos.x = mouseX, .pos.y = mouseY };
    while ( pCurListener != null ) {
        if ( EventListener_getType(pCurListener) == mouseEvent ) {
            EventListener_actionPerformed(pCurListener, sprite, &mouseEventParams);
        }
        pCurListener = EventListener_getNext(pCurListener);
    }
} /* FlexButton_updateMouseState */

/** @public @memberof FlexButton */
bool FlexButton_IsInRect(
    FlexButton* pFlexButton,
    MouseEventParams* pEventPrams
){
    FlexButton* sprite = pFlexButton;
    int mouseX = pEventPrams->pos.x;
    int mouseY = pEventPrams->pos.y;
    SDL_Rect rect = sprite->m_rect;
    rect.x += sprite->m_offset.x;
    rect.y += sprite->m_offset.y;

    if ( mouseX >= rect.x && mouseX < rect.x + rect.w &&
        mouseY >= rect.y && mouseY < rect.y + rect.h
        ) {
        return true;
    }
    return false;
} /* FlexButton_IsInRect */

/** @public @memberof FlexButton */
bool FlexButton_OnPushBtnPressed(
    FlexButton* pFlexButton
){
    pFlexButton->m_value = pFlexButton->m_valueTmp;
    FlexButton* sprite = pFlexButton;
    EventListener* pCurListener = sprite->m_buttonListeners;
    while ( pCurListener != null ) {
        if ( EventListener_getType(pCurListener) == MDD_ON_CLICK ) {
            EventListener_actionPerformed(pCurListener, sprite, null);
        }
        pCurListener = EventListener_getNext(pCurListener);
    }
} /* FlexButton_OnPushBtnPressed */

/** @public @memberof FlexButton */
void FlexButton_OnHoldEntry(
    FlexButton* pFlexButton
){
    pFlexButton->m_value = pFlexButton->m_valueTmp;
    FlexButton* sprite = pFlexButton;
    EventListener* pCurListener = sprite->m_buttonListeners;
    while ( pCurListener != null ) {
        if ( EventListener_getType(pCurListener) == MDD_ON_MOUSE_DOWN ) {
            EventListener_actionPerformed(pCurListener, sprite, null);
        }
        pCurListener = EventListener_getNext(pCurListener);
    }
} /* FlexButton_OnHoldEntry */

/** @public @memberof FlexButton */
void FlexButton_OnHoldExit(
    FlexButton* pFlexButton
){
    pFlexButton->m_value = pFlexButton->m_valueTmp;
    FlexButton* sprite = pFlexButton;
    EventListener* pCurListener = sprite->m_buttonListeners;
    while ( pCurListener != null ) {
        if ( EventListener_getType(pCurListener) == MDD_ON_MOUSE_UP ) {
            EventListener_actionPerformed(pCurListener, sprite, null);
        }
        pCurListener = EventListener_getNext(pCurListener);
    }
} /* FlexButton_OnHoldExit */

/** @public @memberof FlexButton */
void FlexButton_DrawPushStyle(
    FlexButton* pFlexButton,
    SDL_Renderer* renderer
){
    int x = pFlexButton->m_rect.x + pFlexButton->m_rect.w / 2;
    int y = pFlexButton->m_rect.y + pFlexButton->m_rect.h / 2;
    int r = pFlexButton->m_rect.w > pFlexButton->m_rect.h ? pFlexButton->m_rect.h / 2 : pFlexButton->m_rect.w / 2;
    circleRGBA(renderer, x, y, r, 0x00, 0x00, 0x00, 0xFF);
    filledCircleRGBA(renderer, x, y, r - 4, 0x00, 0x00, 0x00, 0xFF);

} /* FlexButton_DrawPushStyle */

/** @public @memberof FlexButton */
void FlexButton_DrawSelectStyle(
    FlexButton* pFlexButton,
    SDL_Renderer* renderer
){
    int x = pFlexButton->m_rect.x + pFlexButton->m_rect.w / 2;
    int r = pFlexButton->m_rect.h / (pFlexButton->m_valueMax * 2);
    for ( int i = 0; i < pFlexButton->m_valueMax; i++ ) {
        int y = pFlexButton->m_rect.y + r + i * 2 * r;
        circleRGBA(renderer, x, y, r, 0x00, 0x00, 0x00, 0xFF);
    }
} /* FlexButton_DrawSelectStyle */

/** @public @memberof FlexButton */
void FlexButton_DrawToggleStyle(
    FlexButton* pFlexButton,
    SDL_Renderer* renderer
){
    int r = pFlexButton->m_rect.h / 2;
    int x1 = pFlexButton->m_rect.x + r;
    int y = pFlexButton->m_rect.y + r;
    arcRGBA(renderer, x1, y, r, 90, 279, 0x00, 0x00, 0x00, 0xFF);

    int x2 = pFlexButton->m_rect.x + pFlexButton->m_rect.w - r;
    arcRGBA(renderer, x2, y, r, -90, 90, 0x00, 0x00, 0x00, 0xFF);

    y = pFlexButton->m_rect.y;
    lineRGBA(renderer, x1, y, x2, y, 0x00, 0x00, 0x00, 0xFF);

    y = pFlexButton->m_rect.y + pFlexButton->m_rect.h;
    lineRGBA(renderer, x1, y, x2, y, 0x00, 0x00, 0x00, 0xFF);
} /* FlexButton_DrawToggleStyle */

/** @public @memberof FlexButton */
void FlexButton_DrawSlideStyle(
    FlexButton* pFlexButton,
    SDL_Renderer* renderer
){
    int r = pFlexButton->m_rect.h / 2;
    int x1 = pFlexButton->m_rect.x + r;
    int y = pFlexButton->m_rect.y + r;
    arcRGBA(renderer, x1, y, r, 90, 279, 0x00, 0x00, 0x00, 0xFF);

    int x2 = pFlexButton->m_rect.x + pFlexButton->m_rect.w - r;
    arcRGBA(renderer, x2, y, r, -90, 90, 0x00, 0x00, 0x00, 0xFF);

    y = pFlexButton->m_rect.y;
    lineRGBA(renderer, x1, y, x2, y, 0x00, 0x00, 0x00, 0xFF);

    y = pFlexButton->m_rect.y + pFlexButton->m_rect.h;
    lineRGBA(renderer, x1, y, x2, y, 0x00, 0x00, 0x00, 0xFF);
} /* FlexButton_DrawSlideStyle */

/** @public @memberof FlexButton */
void FlexButton_DrawPressed(
    FlexButton* pFlexButton,
    SDL_Renderer* renderer
){
    int currentValue = pFlexButton->m_valueTmp;
    if ( pFlexButton->m_rect.h >= pFlexButton->m_rect.w ) {
        int x = pFlexButton->m_rect.x + pFlexButton->m_rect.w / 2;
        int r = pFlexButton->m_rect.w / 2;
        int clampKnopY = pFlexButton->m_knobPos.y - (pFlexButton->m_rect.y + r);
        if ( clampKnopY < 0 ) {
            clampKnopY = 0;
        }
        if ( clampKnopY > pFlexButton->m_rect.h - 2 * r ) {
            clampKnopY = pFlexButton->m_rect.h - 2 * r;
        }
        pFlexButton->m_valueTmp = 0;
        if ( (pFlexButton->m_rect.h - 2 * r) != 0 && pFlexButton->m_valueMax > 1 ) {
            pFlexButton->m_valueTmp = ((pFlexButton->m_valueMax - 1) * clampKnopY + (pFlexButton->m_rect.h - 2 * r) / 2) / (pFlexButton->m_rect.h - 2 * r);
            clampKnopY = (pFlexButton->m_valueTmp * (pFlexButton->m_rect.h - 2 * r) + (pFlexButton->m_valueMax - 1) / 2) / (pFlexButton->m_valueMax - 1);
        }
        int y = pFlexButton->m_rect.y + r + clampKnopY;
        r = r - 4;
        filledCircleRGBA(renderer, x, y, r, 0xFF, 0xFF, 0xFF, 0xFF);
        circleRGBA(renderer, x, y, r, 0x00, 0x00, 0x00, 0xFF);
    }
    else {
        int y = pFlexButton->m_rect.y + pFlexButton->m_rect.h / 2;
        int r = pFlexButton->m_rect.h / 2;
        int clampKnopX = pFlexButton->m_knobPos.x - (pFlexButton->m_rect.x + r);
        if ( clampKnopX < 0 ) {
            clampKnopX = 0;
        }
        if ( clampKnopX > pFlexButton->m_rect.w - 2 * r ) {
            clampKnopX = pFlexButton->m_rect.w - 2 * r;
        }
        pFlexButton->m_valueTmp = 0;
        if ( (pFlexButton->m_rect.w - 2 * r) != 0 && pFlexButton->m_valueMax > 1 ) {
            pFlexButton->m_valueTmp = ((pFlexButton->m_valueMax - 1) * clampKnopX + (pFlexButton->m_rect.w - 2 * r) / 2) / (pFlexButton->m_rect.w - 2 * r);
            clampKnopX = (pFlexButton->m_valueTmp * (pFlexButton->m_rect.w - 2 * r) + (pFlexButton->m_valueMax - 1) / 2) / (pFlexButton->m_valueMax - 1);
        }
        int x = pFlexButton->m_rect.x + r + clampKnopX;
        r = r - 4;
        filledCircleRGBA(renderer, x, y, r, 0xFF, 0xFF, 0xFF, 0xFF);
        circleRGBA(renderer, x, y, r, 0x00, 0x00, 0x00, 0xFF);
    }
    if ( currentValue != pFlexButton->m_valueTmp ) {
        FlexButton* sprite = pFlexButton;
        EventListener* pCurListener = sprite->m_buttonListeners;
        while ( pCurListener != null ) {
            if ( EventListener_getType(pCurListener) == MDD_ON_VALUE_CHANGED ) {
                pFlexButton->m_value = pFlexButton->m_valueTmp;
                EventListener_actionPerformed(pCurListener, sprite, null);
            }
            pCurListener = EventListener_getNext(pCurListener);
        }
    }
} /* FlexButton_DrawPressed */

/** @public @memberof FlexButton */
void FlexButton_DrawKnob(
    FlexButton* pFlexButton,
    SDL_Renderer* renderer
){
    if ( pFlexButton->m_rect.h >= pFlexButton->m_rect.w && pFlexButton->m_valueMax > 1 ) {
        int x = pFlexButton->m_rect.x + pFlexButton->m_rect.w / 2;
        int r = pFlexButton->m_rect.w / 2;
        int clampKnopY = 0;
        if ( (pFlexButton->m_rect.h - 2 * r) != 0 ) {
            clampKnopY = (pFlexButton->m_value * (pFlexButton->m_rect.h - 2 * r) + (pFlexButton->m_valueMax - 1) / 2) / (pFlexButton->m_valueMax - 1);
        }
        int y = pFlexButton->m_rect.y + r + clampKnopY;
        r = r - 4;
        filledCircleRGBA(renderer, x, y, r, 0x00, 0x00, 0x00, 0xFF);
    }
    else {
        int y = pFlexButton->m_rect.y + pFlexButton->m_rect.h / 2;
        int r = pFlexButton->m_rect.h / 2;
        int clampKnopX = 0;
        if ( (pFlexButton->m_rect.w - 2 * r) != 0 && pFlexButton->m_valueMax > 1 ) {
            clampKnopX = (pFlexButton->m_value * (pFlexButton->m_rect.w - 2 * r) + (pFlexButton->m_valueMax - 1) / 2) / (pFlexButton->m_valueMax - 1);
        }
        int x = pFlexButton->m_rect.x + r + clampKnopX;
        r = r - 4;
        filledCircleRGBA(renderer, x, y, r, 0x00, 0x00, 0x00, 0xFF);
    }
} /* FlexButton_DrawKnob */

/** @public @memberof FlexButton */
int FlexButton_GetValue(
    FlexButton* pFlexButton
){
    return pFlexButton->m_value;
} /* FlexButton_GetValue */

/** @public @memberof FlexButton */
void FlexButton_SetValue(
    FlexButton* pFlexButton,
    int value
){
    pFlexButton->m_value = value;
} /* FlexButton_SetValue */

const TCHAR* FlexButtonEvent_toString( FlexButton_EVENT value ){
    switch( value ){
    case FlexButton_DRAW0: return _T( "DRAW0" );
    case FlexButton_DRAW1: return _T( "DRAW1" );
    case FlexButton_MOUSE_DOWN: return _T( "MOUSE_DOWN" );
    case FlexButton_MOUSE_MOVE: return _T( "MOUSE_MOVE" );
    case FlexButton_MOUSE_UP: return _T( "MOUSE_UP" );
    default: return _T( "FlexButton_UNKNOWN" );
    }
}
static BOOL FlexBtnTop_Reset( FlexButton* pFlexButton, FlexBtnTop* pUsm, BOOL lastEnteredStateRecovering, uint64_t entryPt );
static void FlexBtnTop_Prepare( FlexBtnTop* pUsm, HdStateMachine* pParent );
static BOOL FlexBtnTop_EventProc( FlexButton* pFlexButton, FlexBtnTop* pUsm, FlexButton_EVENT nEventId, void* pEventParams );
static BOOL FlexBtnTop_StateDefaultTrans( FlexButton* pFlexButton, FlexBtnTop* pUsm );
BOOL FlexButton_Start( FlexButton* pFlexButton ){
    FlexBtnTop_Prepare( &pFlexButton->mainStm, NULL );
    BOOL bResult = FlexBtnTop_Reset( pFlexButton, &pFlexButton->mainStm, FALSE, STATE_UNDEF );
    bResult |= FlexBtnTop_StateDefaultTrans( pFlexButton, &pFlexButton->mainStm );
    return bResult;
}
BOOL FlexButton_EventProc( FlexButton* pFlexButton, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FlexBtnTop_EventProc( pFlexButton, &pFlexButton->mainStm, nEventId, pEventParams );
    bResult |= FlexBtnTop_StateDefaultTrans( pFlexButton, &pFlexButton->mainStm );
    return bResult;
}

/**
 * Implementation for Statemachine: FlexBtnTop
 */
static void FlexBtnStmHsm_BgnTrans( FlexButton *pFlexButton, HdStateMachine* pStm, uint64_t targetState );
static void FlexBtnStmHsm_EndTrans( FlexButton *pFlexButton, HdStateMachine* pStm );
static BOOL FlexBtnStmHsm_Abort( FlexButton* pFlexButton, HdStateMachine* pStm );
static BOOL FlexBtnStmHsm_Reset( FlexButton* pFlexButton, HdStateMachine* pStm, BOOL bUnused, uint64_t nEntryPoint );
static BOOL FlexBtnStmHsm_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams );
static void ReadyRgn1Hsm_BgnTrans( FlexButton *pFlexButton, HdStateMachine* pStm, uint64_t targetState );
static void ReadyRgn1Hsm_EndTrans( FlexButton *pFlexButton, HdStateMachine* pStm );
static BOOL ReadyRgn1Hsm_Abort( FlexButton* pFlexButton, HdStateMachine* pStm );
static BOOL ReadyRgn1Hsm_Reset( FlexButton* pFlexButton, HdStateMachine* pStm, BOOL bUnused, uint64_t nEntryPoint );
static BOOL ReadyRgn1Hsm_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams );
static void FlexBtnTop_ReadyRgn1_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_ReadyRgn1 ) ){
        if( pStm->nTargetState == FlexBtnTop_ReadyRgn1 ){
            pStm->nPseudostate = FlexBtnTop_InitialReadyRegion1;
        }
        if ( pStm->lastEnteredStateRecovering ) {
            pStm->nPseudostate = pStm->lastEnteredState;
        }
        //HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "" );
    }
}
static BOOL FlexBtnTop_ReadyRgn1_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_ReadyRgn1;
    //HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "" );
    return bResult;
}
static void FlexBtnTop_ReadyRgn1_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_ReadyRgn1 ) ){ 
        //HdStateMachine_DefaultExitAction( pStm, pFlexButton, "" );
    }
}
static void FlexBtnTop_Missed_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_Missed ) ){
        FlexBtnTop_ReadyRgn1_Entry( pFlexButton, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	627	185	91	50	282	39	848	673" );
    }
}
static BOOL FlexBtnTop_Missed_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_Missed;
    HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	627	185	91	50	282	39	848	673" );
    switch( nEventId ){
    case FlexButton_MOUSE_UP:{
            ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_Idle );
            ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
            bResult = TRUE;
    } break;
    default: break;
    }
    return bResult ? bResult : FlexBtnTop_ReadyRgn1_EventProc( pFlexButton, pStm, nEventId, pEventParams );
}
static void FlexBtnTop_Missed_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_Missed ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	627	185	91	50	282	39	848	673" );
        FlexBtnTop_ReadyRgn1_Exit( pFlexButton, pStm );
    }
}
static void FlexBtnTop_Idle_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_Idle ) ){
        FlexBtnTop_ReadyRgn1_Entry( pFlexButton, pStm );
                pFlexButton->m_knobPos.x = pFlexButton->m_rect.x + pFlexButton->m_rect.w/2;
                pFlexButton->m_knobPos.y = pFlexButton->m_rect.y + pFlexButton->m_rect.h/2;
        HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	803	185	231	106	282	39	848	673" );
    }
}
static BOOL FlexBtnTop_Idle_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_Idle;
    HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	803	185	231	106	282	39	848	673" );
    switch( nEventId ){
    case FlexButton_MOUSE_DOWN:{
                        if (FlexButton_IsInRect( pFlexButton, pEventParams )) {
                ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_Pressed );
                ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
                bResult = TRUE;
            } else {
                ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_Missed );
                ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
                bResult = TRUE;
            }
    } break;
    default: break;
    }
    return bResult ? bResult : FlexBtnTop_ReadyRgn1_EventProc( pFlexButton, pStm, nEventId, pEventParams );
}
static void FlexBtnTop_Idle_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_Idle ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	803	185	231	106	282	39	848	673" );
        FlexBtnTop_ReadyRgn1_Exit( pFlexButton, pStm );
    }
}
static void FlexBtnTop_Hold_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_Hold ) ){
        FlexBtnTop_ReadyRgn1_Entry( pFlexButton, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	804	345	231	304	282	39	848	673" );
    }
}
static BOOL FlexBtnTop_Hold_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_Hold;
    HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	804	345	231	304	282	39	848	673" );
    switch( nEventId ){
    case FlexButton_MOUSE_UP:{
            ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_Idle );
            ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
            bResult = TRUE;
    } break;
    case FlexButton_MOUSE_MOVE:{
                                    MouseEventParams* pParams = ( MouseEventParams* )pEventParams;
                        pFlexButton->m_knobPos = pParams->pos;
                        if (HdStateMachine_IsIn( &( ( FlexBtnTop* )pStm->pMain )->FlexBtnStmHsm, FlexBtnTop_SlideStyle )) {
                ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_Pressed );
                                pFlexButton->m_value = pFlexButton->m_valueTmp;
                ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
                bResult = TRUE;
            } else {
                                if (FlexButton_IsInRect( pFlexButton, pEventParams )) {
                    ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_Pressed );
                    ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
                    bResult = TRUE;
                } else {
                    ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_UnPressed );
                    ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
                    bResult = TRUE;
                }
            }
    } break;
    default: break;
    }
    return bResult ? bResult : FlexBtnTop_ReadyRgn1_EventProc( pFlexButton, pStm, nEventId, pEventParams );
}
static void FlexBtnTop_Hold_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_Hold ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	804	345	231	304	282	39	848	673" );
        FlexBtnTop_ReadyRgn1_Exit( pFlexButton, pStm );
    }
}
static void FlexBtnTop_UnPressed_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_UnPressed ) ){
        FlexBtnTop_Hold_Entry( pFlexButton, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	828	548	181	77	282	39	848	673" );
    }
}
static BOOL FlexBtnTop_UnPressed_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_UnPressed;
    HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	828	548	181	77	282	39	848	673" );
    return bResult ? bResult : FlexBtnTop_Hold_EventProc( pFlexButton, pStm, nEventId, pEventParams );
}
static void FlexBtnTop_UnPressed_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_UnPressed ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	828	548	181	77	282	39	848	673" );
        FlexBtnTop_Hold_Exit( pFlexButton, pStm );
    }
}
static void FlexBtnTop_Pressed_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_Pressed ) ){
        FlexBtnTop_Hold_Entry( pFlexButton, pStm );
        HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	830	370	181	86	282	39	848	673" );
    }
}
static BOOL FlexBtnTop_Pressed_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_Pressed;
    HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	830	370	181	86	282	39	848	673" );
    switch( nEventId ){
    case FlexButton_DRAW1:{
                        FlexButton_DrawPressed(
                            pFlexButton,
                            ( SDL_Renderer* )pEventParams
                        );
            bResult = TRUE; // internal transition
    } break;
    case FlexButton_MOUSE_UP:{
            ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_Idle );
                        FlexButton_OnPushBtnPressed( pFlexButton );
            ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
            bResult = TRUE;
    } break;
    default: break;
    }
    return bResult ? bResult : FlexBtnTop_Hold_EventProc( pFlexButton, pStm, nEventId, pEventParams );
}
static void FlexBtnTop_Pressed_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_Pressed ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	830	370	181	86	282	39	848	673" );
        FlexBtnTop_Hold_Exit( pFlexButton, pStm );
    }
}
static void ReadyRgn1Hsm_BgnTrans( FlexButton *pFlexButton, HdStateMachine* pStm, uint64_t targetState ){
    pStm->nTargetState = targetState;
    pStm->nPseudostate = targetState;
    switch( pStm->nCurrentState ){
    case FlexBtnTop_ReadyRgn1:  FlexBtnTop_ReadyRgn1_Exit( pFlexButton, pStm ); break;
    case FlexBtnTop_Missed:     FlexBtnTop_Missed_Exit( pFlexButton, pStm ); break;
    case FlexBtnTop_Idle:       FlexBtnTop_Idle_Exit( pFlexButton, pStm ); break;
    case FlexBtnTop_UnPressed:  FlexBtnTop_UnPressed_Exit( pFlexButton, pStm ); break;
    case FlexBtnTop_Pressed:    FlexBtnTop_Pressed_Exit( pFlexButton, pStm ); break;
    case FlexBtnTop_Hold:       FlexBtnTop_Hold_Exit( pFlexButton, pStm ); break;
    default: break;
    }
}
static BOOL ReadyRgn1Hsm_Reset( FlexButton* pFlexButton, HdStateMachine* pStm, BOOL bUnused, uint64_t nEntryPoint ) {
    if( nEntryPoint != STATE_UNDEF ){
        pStm->nPseudostate = nEntryPoint;
        return FALSE;
    }else{
        pStm->nPseudostate = FlexBtnTop_ReadyRgn1;
    }
    ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, pStm->nPseudostate );
    ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
    return TRUE;
}
static BOOL ReadyRgn1Hsm_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nLCAState = STATE_UNDEF;
    switch( pStm->nCurrentState ){
    case FlexBtnTop_ReadyRgn1:                  bResult |= FlexBtnTop_ReadyRgn1_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    case FlexBtnTop_Missed:                     bResult |= FlexBtnTop_Missed_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    case FlexBtnTop_Idle:                       bResult |= FlexBtnTop_Idle_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    case FlexBtnTop_UnPressed:                  bResult |= FlexBtnTop_UnPressed_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    case FlexBtnTop_Pressed:                    bResult |= FlexBtnTop_Pressed_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    case FlexBtnTop_Hold:                       bResult |= FlexBtnTop_Hold_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    default: break;
    }
    return bResult;
}
static BOOL ReadyRgn1Hsm_Abort( FlexButton* pFlexButton, HdStateMachine* pStm ) {
    pStm->nSourceState = FlexBtnTop_ReadyRgn1;
    ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_ReadyRgn1 );
    ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
    return TRUE;
}
static void ReadyRgn1Hsm_EndTrans( FlexButton *pFlexButton, HdStateMachine* pStm ){
    pStm->nCurrentState = pStm->nTargetState;
    pStm->bIsExternTrans = FALSE;
    switch( pStm->nCurrentState ){
    case FlexBtnTop_ReadyRgn1:  FlexBtnTop_ReadyRgn1_Entry( pFlexButton, pStm ); break;
    case FlexBtnTop_Missed:     FlexBtnTop_Missed_Entry( pFlexButton, pStm ); break;
    case FlexBtnTop_Idle:       FlexBtnTop_Idle_Entry( pFlexButton, pStm ); break;
    case FlexBtnTop_UnPressed:  FlexBtnTop_UnPressed_Entry( pFlexButton, pStm ); break;
    case FlexBtnTop_Pressed:    FlexBtnTop_Pressed_Entry( pFlexButton, pStm ); break;
    case FlexBtnTop_Hold:       FlexBtnTop_Hold_Entry( pFlexButton, pStm ); break;
    default: break;
    }
}
static BOOL ReadyRgn1Hsm_StateDefaultTrans( FlexButton* pFlexButton, HdStateMachine* pStm ){
    BOOL bResult = FALSE;
    pStm->nSourceState = pStm->nCurrentState;
    pStm->nLCAState = STATE_UNDEF;
        if( pStm->nCurrentState == FlexBtnTop_ReadyRgn1 && pStm->nPseudostate == FlexBtnTop_InitialReadyRegion1  ){
            ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_Idle );
            ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
            bResult = TRUE;
        }else if( pStm->nCurrentState != pStm->nPseudostate ){
            ReadyRgn1Hsm_BgnTrans( pFlexButton, pStm, pStm->nPseudostate );
            ReadyRgn1Hsm_EndTrans( pFlexButton, pStm );
            bResult = TRUE;
        }else{
        }
    return bResult;
}
static void FlexBtnTop_FlexBtnStm_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_FlexBtnStm ) ){
        if( pStm->nTargetState == FlexBtnTop_FlexBtnStm ){
            pStm->nPseudostate = FlexBtnTop_InitialMain;
        }
        if ( pStm->lastEnteredStateRecovering ) {
            pStm->nPseudostate = pStm->lastEnteredState;
        }
        //HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "" );
    }
}
static BOOL FlexBtnTop_FlexBtnStm_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_FlexBtnStm;
    //HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "" );
    return bResult;
}
static void FlexBtnTop_FlexBtnStm_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_FlexBtnStm ) ){ 
        //HdStateMachine_DefaultExitAction( pStm, pFlexButton, "" );
    }
}
static void FlexBtnTop_Ready_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_Ready ) ){
        FlexBtnTop_FlexBtnStm_Entry( pFlexButton, pStm );
        if( pStm->nTargetState == FlexBtnTop_Ready ){
            pStm->nPseudostate = FlexBtnTop_InitialReady;
        }
        ReadyRgn1Hsm_Reset( pFlexButton, &( ( FlexBtnTop* )pStm->pMain )->ReadyRgn1Hsm, FALSE, STATE_UNDEF );
        HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	322	122	759	565	282	39	848	673" );
    }
}
static BOOL FlexBtnTop_Ready_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_Ready;
    HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	322	122	759	565	282	39	848	673" );
    switch( nEventId ){
    case FlexButton_DRAW1:{
                        FlexButton_DrawKnob(
                            pFlexButton,
                            ( SDL_Renderer* )pEventParams
                        );
            bResult = TRUE; // internal transition
    } break;
    default: break;
    }
    return bResult ? bResult : FlexBtnTop_FlexBtnStm_EventProc( pFlexButton, pStm, nEventId, pEventParams );
}
static void FlexBtnTop_Ready_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_Ready ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	322	122	759	565	282	39	848	673" );
        ReadyRgn1Hsm_Abort( pFlexButton, &( ( FlexBtnTop* )pStm->pMain )->ReadyRgn1Hsm );
        FlexBtnTop_FlexBtnStm_Exit( pFlexButton, pStm );
    }
}
static void FlexBtnTop_ToggleStyle_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_ToggleStyle ) ){
        FlexBtnTop_Ready_Entry( pFlexButton, pStm );
        ( ( FlexBtnTop* )pStm->pMain )->nReadyHistory = FlexBtnTop_ToggleStyle;
        HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	434	200	84	282	39	848	673" );
    }
}
static BOOL FlexBtnTop_ToggleStyle_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_ToggleStyle;
    HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	434	200	84	282	39	848	673" );
    switch( nEventId ){
    case FlexButton_DRAW0:{
                        FlexButton_DrawToggleStyle(
                            pFlexButton,
                            ( SDL_Renderer* )pEventParams
                        );
            bResult = TRUE; // internal transition
    } break;
    default: break;
    }
    return bResult ? bResult : FlexBtnTop_Ready_EventProc( pFlexButton, pStm, nEventId, pEventParams );
}
static void FlexBtnTop_ToggleStyle_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_ToggleStyle ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	434	200	84	282	39	848	673" );
        FlexBtnTop_Ready_Exit( pFlexButton, pStm );
    }
}
static void FlexBtnTop_SelectStyle_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_SelectStyle ) ){
        FlexBtnTop_Ready_Entry( pFlexButton, pStm );
        ( ( FlexBtnTop* )pStm->pMain )->nReadyHistory = FlexBtnTop_SelectStyle;
        HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	320	200	84	282	39	848	673" );
    }
}
static BOOL FlexBtnTop_SelectStyle_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_SelectStyle;
    HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	320	200	84	282	39	848	673" );
    switch( nEventId ){
    case FlexButton_DRAW0:{
                        FlexButton_DrawSelectStyle(
                            pFlexButton,
                            ( SDL_Renderer* )pEventParams
                        );
            bResult = TRUE; // internal transition
    } break;
    default: break;
    }
    return bResult ? bResult : FlexBtnTop_Ready_EventProc( pFlexButton, pStm, nEventId, pEventParams );
}
static void FlexBtnTop_SelectStyle_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_SelectStyle ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	320	200	84	282	39	848	673" );
        FlexBtnTop_Ready_Exit( pFlexButton, pStm );
    }
}
static void FlexBtnTop_SlideStyle_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_SlideStyle ) ){
        FlexBtnTop_Ready_Entry( pFlexButton, pStm );
        ( ( FlexBtnTop* )pStm->pMain )->nReadyHistory = FlexBtnTop_SlideStyle;
        HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	548	200	84	282	39	848	673" );
    }
}
static BOOL FlexBtnTop_SlideStyle_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_SlideStyle;
    HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	548	200	84	282	39	848	673" );
    switch( nEventId ){
    case FlexButton_DRAW0:{
                        FlexButton_DrawSlideStyle(
                            pFlexButton,
                            ( SDL_Renderer* )pEventParams
                        );
            bResult = TRUE; // internal transition
    } break;
    default: break;
    }
    return bResult ? bResult : FlexBtnTop_Ready_EventProc( pFlexButton, pStm, nEventId, pEventParams );
}
static void FlexBtnTop_SlideStyle_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_SlideStyle ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	548	200	84	282	39	848	673" );
        FlexBtnTop_Ready_Exit( pFlexButton, pStm );
    }
}
static void FlexBtnTop_PushStyle_Entry( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Enterable( pStm, FlexBtnTop_PushStyle ) ){
        FlexBtnTop_Ready_Entry( pFlexButton, pStm );
        ( ( FlexBtnTop* )pStm->pMain )->nReadyHistory = FlexBtnTop_PushStyle;
        HdStateMachine_DefaultEntryAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	191	200	115	282	39	848	673" );
    }
}
static BOOL FlexBtnTop_PushStyle_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nSourceState = FlexBtnTop_PushStyle;
    HdStateMachine_DefaultDoingAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	191	200	115	282	39	848	673" );
    switch( nEventId ){
    case FlexButton_DRAW0:{
                        FlexButton_DrawPushStyle(
                            pFlexButton,
                            ( SDL_Renderer* )pEventParams
                        );
            bResult = TRUE; // internal transition
    } break;
    case FlexButton_DRAW1:{
            if (HdStateMachine_IsIn( &((FlexBtnTop*)pStm->pMain)->ReadyRgn1Hsm, FlexBtnTop_Pressed)) {
                bResult = TRUE; // internal transition
            }
    } break;
    default: break;
    }
    return bResult ? bResult : FlexBtnTop_Ready_EventProc( pFlexButton, pStm, nEventId, pEventParams );
}
static void FlexBtnTop_PushStyle_Exit( FlexButton* pFlexButton, HdStateMachine* pStm ){
    if( HdStateMachine_Exitable( pStm, FlexBtnTop_PushStyle ) ){ 
        HdStateMachine_DefaultExitAction( pStm, pFlexButton, "Model/FlexButton/FlexBtnTop	353	191	200	115	282	39	848	673" );
        FlexBtnTop_Ready_Exit( pFlexButton, pStm );
    }
}
static void FlexBtnStmHsm_BgnTrans( FlexButton *pFlexButton, HdStateMachine* pStm, uint64_t targetState ){
    pStm->nTargetState = targetState;
    pStm->nPseudostate = targetState;
    switch( pStm->nCurrentState ){
    case FlexBtnTop_FlexBtnStm: FlexBtnTop_FlexBtnStm_Exit( pFlexButton, pStm ); break;
    case FlexBtnTop_ToggleStyle:FlexBtnTop_ToggleStyle_Exit( pFlexButton, pStm ); break;
    case FlexBtnTop_SelectStyle:FlexBtnTop_SelectStyle_Exit( pFlexButton, pStm ); break;
    case FlexBtnTop_SlideStyle: FlexBtnTop_SlideStyle_Exit( pFlexButton, pStm ); break;
    case FlexBtnTop_PushStyle:  FlexBtnTop_PushStyle_Exit( pFlexButton, pStm ); break;
    case FlexBtnTop_Ready:      FlexBtnTop_Ready_Exit( pFlexButton, pStm ); break;
    default: break;
    }
}
static BOOL FlexBtnStmHsm_Reset( FlexButton* pFlexButton, HdStateMachine* pStm, BOOL bUnused, uint64_t nEntryPoint ) {
    if( nEntryPoint != STATE_UNDEF ){
        pStm->nPseudostate = nEntryPoint;
        return FALSE;
    }else{
        pStm->nPseudostate = FlexBtnTop_FlexBtnStm;
    }
    FlexBtnStmHsm_BgnTrans( pFlexButton, pStm, pStm->nPseudostate );
    FlexBtnStmHsm_EndTrans( pFlexButton, pStm );
    return TRUE;
}
static BOOL FlexBtnStmHsm_EventProc( FlexButton* pFlexButton, HdStateMachine* pStm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    pStm->nLCAState = STATE_UNDEF;
    switch( pStm->nCurrentState ){
    case FlexBtnTop_FlexBtnStm:                 bResult |= FlexBtnTop_FlexBtnStm_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    case FlexBtnTop_ToggleStyle:                bResult |= FlexBtnTop_ToggleStyle_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    case FlexBtnTop_SelectStyle:                bResult |= FlexBtnTop_SelectStyle_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    case FlexBtnTop_SlideStyle:                 bResult |= FlexBtnTop_SlideStyle_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    case FlexBtnTop_PushStyle:                  bResult |= FlexBtnTop_PushStyle_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    case FlexBtnTop_Ready:                      bResult |= FlexBtnTop_Ready_EventProc( pFlexButton, pStm, nEventId, pEventParams ); break;
    default: break;
    }
    return bResult;
}
static BOOL FlexBtnStmHsm_Abort( FlexButton* pFlexButton, HdStateMachine* pStm ) {
    pStm->nSourceState = FlexBtnTop_FlexBtnStm;
    FlexBtnStmHsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_FlexBtnStm );
    FlexBtnStmHsm_EndTrans( pFlexButton, pStm );
    return TRUE;
}
static void FlexBtnStmHsm_EndTrans( FlexButton *pFlexButton, HdStateMachine* pStm ){
    pStm->nCurrentState = pStm->nTargetState;
    pStm->bIsExternTrans = FALSE;
    switch( pStm->nCurrentState ){
    case FlexBtnTop_FlexBtnStm: FlexBtnTop_FlexBtnStm_Entry( pFlexButton, pStm ); break;
    case FlexBtnTop_ToggleStyle:FlexBtnTop_ToggleStyle_Entry( pFlexButton, pStm ); break;
    case FlexBtnTop_SelectStyle:FlexBtnTop_SelectStyle_Entry( pFlexButton, pStm ); break;
    case FlexBtnTop_SlideStyle: FlexBtnTop_SlideStyle_Entry( pFlexButton, pStm ); break;
    case FlexBtnTop_PushStyle:  FlexBtnTop_PushStyle_Entry( pFlexButton, pStm ); break;
    case FlexBtnTop_Ready:      FlexBtnTop_Ready_Entry( pFlexButton, pStm ); break;
    default: break;
    }
}
static BOOL FlexBtnStmHsm_StateDefaultTrans( FlexButton* pFlexButton, HdStateMachine* pStm ){
    BOOL bResult = FALSE;
    pStm->nSourceState = pStm->nCurrentState;
    pStm->nLCAState = STATE_UNDEF;
        if( pStm->nCurrentState == FlexBtnTop_Ready && pStm->nPseudostate == FlexBtnTop_InitialReady  ){
                        if( ( ( FlexBtnTop* )pStm->pMain )->nReadyHistory != STATE_UNDEF ){
                FlexBtnStmHsm_BgnTrans( pFlexButton, pStm, ( ( FlexBtnTop* )pStm->pMain )->nReadyHistory );
                FlexBtnStmHsm_EndTrans( pFlexButton, pStm );
                bResult = TRUE;
            }else{
                FlexBtnStmHsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_PushStyle );
                FlexBtnStmHsm_EndTrans( pFlexButton, pStm );
                bResult = TRUE;
            }
        }else if( pStm->nCurrentState == FlexBtnTop_FlexBtnStm && pStm->nPseudostate == FlexBtnTop_InitialMain  ){
            FlexBtnStmHsm_BgnTrans( pFlexButton, pStm, FlexBtnTop_Ready );
                        ( ( FlexBtnTop* )pStm->pMain )->nReadyHistory = pFlexButton->m_style;
            FlexBtnStmHsm_EndTrans( pFlexButton, pStm );
            bResult = TRUE;
        }else if( pStm->nCurrentState != pStm->nPseudostate ){
            FlexBtnStmHsm_BgnTrans( pFlexButton, pStm, pStm->nPseudostate );
            FlexBtnStmHsm_EndTrans( pFlexButton, pStm );
            bResult = TRUE;
        }else{
        }
    return bResult;
}
static BOOL FlexBtnTop_EventProc( FlexButton* pFlexButton, FlexBtnTop* pUsm, FlexButton_EVENT nEventId, void* pEventParams ){
    BOOL bResult = FALSE;
    bResult |= ReadyRgn1Hsm_EventProc( pFlexButton, &pUsm->ReadyRgn1Hsm, nEventId, pEventParams );
    bResult |= FlexBtnStmHsm_EventProc( pFlexButton, &pUsm->FlexBtnStmHsm, nEventId, pEventParams );
    return bResult;
}
static BOOL FlexBtnTop_StateDefaultTrans( FlexButton* pFlexButton, FlexBtnTop* pUsm ){
    BOOL bResult;
    while( TRUE ){
        bResult = FALSE;
        bResult |= ReadyRgn1Hsm_StateDefaultTrans( pFlexButton, &pUsm->ReadyRgn1Hsm );
        bResult |= FlexBtnStmHsm_StateDefaultTrans( pFlexButton, &pUsm->FlexBtnStmHsm );
        if( bResult == FALSE ){
            break;
        }
    }
    return bResult;
}
static BOOL FlexBtnTop_Reset( FlexButton* pFlexButton, FlexBtnTop* pUsm, BOOL lastEnteredStateRecovering, uint64_t entryPt ){
    pUsm->lastEnteredStateRecovering = lastEnteredStateRecovering;
    return FlexBtnStmHsm_Reset( pFlexButton, &pUsm->FlexBtnStmHsm, FALSE, entryPt );
}
static BOOL FlexBtnTop_Abort( FlexButton* pFlexButton, FlexBtnTop* pUsm ){
    return FlexBtnStmHsm_Abort( pFlexButton, &pUsm->FlexBtnStmHsm );
}

static void FlexBtnTop_Prepare( FlexBtnTop* pUsm, HdStateMachine* pParent ){
    pUsm->pParentStm = pParent;
    pUsm->FlexBtnStmHsm.pMain = pUsm;
    pUsm->ReadyRgn1Hsm.pMain = pUsm;
}
Sprite* FlexButton_Copy( FlexButton* pFlexButton, const FlexButton* pSource ){
    Sprite_Copy( ( Sprite* )pFlexButton, ( Sprite* )pSource );
    pFlexButton->m_value = pSource->m_value;
    pFlexButton->m_valueMax = pSource->m_valueMax;
    pFlexButton->m_valueTmp = pSource->m_valueTmp;
    pFlexButton->m_style = pSource->m_style;
    pFlexButton->m_knobPos = pSource->m_knobPos;
    pFlexButton->m_mouseListeners = pSource->m_mouseListeners;
    pFlexButton->m_buttonListeners = pSource->m_buttonListeners;
    return ( Sprite* )pFlexButton;
}
const SpriteVtbl gFlexButtonVtbl = {
    .pload                       = FlexButton_load,
    .pdraw0                      = FlexButton_draw0,
    .pdraw1                      = FlexButton_draw1,
    .pupdateMouseState           = FlexButton_updateMouseState,
};
